/* 1001 件人类艺术瑰宝 — 数据集
   curated: 精选真实著名作品，附 Wikimedia Commons 缩略图。
   其余条目由真实艺术家 / 时代目录程序化生成，凑足 1001 件。
   每条字段: id,title,artist,year,era,medium,country,location,desc,img
*/

// 工具：构造 Wikimedia 缩略图 URL
function wm(file, w){ return "https://commons.wikimedia.org/wiki/Special:FilePath/" + encodeURIComponent(file) + "?width=" + (w||500); }

// —— 精选真实著名作品（带真实图片）——
const CURATED = [
  {title:"蒙娜丽莎",artist:"列奥纳多·达·芬奇",year:"约1503–1506",era:"文艺复兴",medium:"木板油画",country:"意大利",location:"巴黎卢浮宫",desc:"世界上最著名的肖像画，以神秘的微笑与精妙的渐隐法（sfumato）著称。",img:wm("Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg")},
  {title:"星月夜",artist:"文森特·梵高",year:"1889",era:"后印象派",medium:"布面油画",country:"荷兰",location:"纽约现代艺术博物馆",desc:"梵高在圣雷米精神疗养院窗外所见夜空的漩涡式狂想，是表现主义的先声。",img:wm("Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg")},
  {title:"呐喊",artist:"爱德华·蒙克",year:"1893",era:"表现主义",medium:"纸板蛋彩与蜡笔",country:"挪威",location:"奥斯陆国家美术馆",desc:"现代人焦虑与存在恐惧的象征性形象，扭曲的天空回荡着无声的尖叫。",img:wm("Edvard_Munch,_1893,_The_Scream,_oil,_tempera_and_pastel_on_cardboard,_91_x_73_cm,_National_Gallery_of_Norway.jpg")},
  {title:"戴珍珠耳环的少女",artist:"约翰内斯·维米尔",year:"约1665",era:"巴洛克",medium:"布面油画",country:"荷兰",location:"海牙莫瑞泰斯皇家美术馆",desc:"被誉为「北方的蒙娜丽莎」，少女回眸的瞬间与一点珍珠高光令人难忘。",img:wm("1665_Girl_with_a_Pearl_Earring.jpg")},
  {title:"格尔尼卡",artist:"巴勃罗·毕加索",year:"1937",era:"现代主义",medium:"布面油画",country:"西班牙",location:"马德里索菲亚王后国家艺术中心",desc:"为抗议格尔尼卡小镇遭轰炸而作，黑白灰构成的立体主义反战巨作。",img:wm("PicassoGuernica.jpg")},
  {title:"维纳斯的诞生",artist:"桑德罗·波提切利",year:"约1485",era:"文艺复兴",medium:"布面蛋彩",country:"意大利",location:"佛罗伦萨乌菲齐美术馆",desc:"女神维纳斯从海中贝壳诞生，体现新柏拉图主义对神圣之美的颂扬。",img:wm("Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg")},
  {title:"创造亚当",artist:"米开朗基罗",year:"约1512",era:"文艺复兴",medium:"湿壁画",country:"意大利",location:"梵蒂冈西斯廷礼拜堂",desc:"上帝与亚当指尖即将相触，西方艺术中最具标志性的形象之一。",img:wm("Michelangelo_-_Creation_of_Adam_(cropped).jpg")},
  {title:"夜巡",artist:"伦勃朗·范·莱因",year:"1642",era:"巴洛克",medium:"布面油画",country:"荷兰",location:"阿姆斯特丹国立博物馆",desc:"群像中迸发的戏剧性光影与动势，打破了传统民兵肖像的呆板。",img:wm("The_Night_Watch_-_HD.jpg")},
  {title:"记忆的永恒",artist:"萨尔瓦多·达利",year:"1931",era:"超现实主义",medium:"布面油画",country:"西班牙",location:"纽约现代艺术博物馆",desc:"软化垂落的钟表，对时间、记忆与潜意识的超现实诘问。",img:wm("The_Persistence_of_Memory.jpg")},
  {title:"自由引导人民",artist:"欧仁·德拉克罗瓦",year:"1830",era:"浪漫主义",medium:"布面油画",country:"法国",location:"巴黎卢浮宫",desc:"自由女神高举三色旗领民众前行，七月革命的浪漫主义图腾。",img:wm("Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg")},
  {title:"睡莲",artist:"克劳德·莫奈",year:"约1916",era:"印象派",medium:"布面油画",country:"法国",location:"巴黎橘园美术馆",desc:"莫奈晚年在吉维尼花园对水面光色的沉浸式描绘，近乎抽象。",img:wm("Claude_Monet_-_Water_Lilies_-_1906,_Ryerson.jpg")},
  {title:"日出·印象",artist:"克劳德·莫奈",year:"1872",era:"印象派",medium:"布面油画",country:"法国",location:"巴黎马蒙坦莫奈美术馆",desc:"「印象派」一词的来源，勒阿弗尔港晨雾中的红日。",img:wm("Monet_-_Impression,_Sunrise.jpg")},
  {title:"吻",artist:"古斯塔夫·克里姆特",year:"1907–1908",era:"象征主义",medium:"布面油画与金箔",country:"奥地利",location:"维也纳美景宫",desc:"金色时期的巅峰，恋人相拥被华美的金箔纹样包裹。",img:wm("The_Kiss_-_Gustav_Klimt_-_Google_Cultural_Institute.jpg")},
  {title:"美国哥特式",artist:"格兰特·伍德",year:"1930",era:"地方主义",medium:"纤维板油画",country:"美国",location:"芝加哥艺术博物馆",desc:"持干草叉的农夫与女子，对美国乡土精神既庄严又含讽喻。",img:wm("Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg")},
  {title:"大碗岛的星期天下午",artist:"乔治·修拉",year:"1884–1886",era:"后印象派",medium:"布面油画",country:"法国",location:"芝加哥艺术博物馆",desc:"点彩派的代表，以无数色点构筑出宁静的塞纳河畔休闲图景。",img:wm("A_Sunday_on_La_Grande_Jatte,_Georges_Seurat,_1884.jpg")},
  {title:"拾穗者",artist:"让-弗朗索瓦·米勒",year:"1857",era:"现实主义",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"三位农妇弯腰拾取麦穗，对劳动者的庄严礼赞。",img:wm("Jean-Fran%C3%A7ois_Millet_-_Gleaners_-_Google_Art_Project_2.jpg")},
  {title:"雅典学院",artist:"拉斐尔",year:"1509–1511",era:"文艺复兴",medium:"湿壁画",country:"意大利",location:"梵蒂冈签字厅",desc:"柏拉图、亚里士多德等古典哲人齐聚，文艺复兴人文理想的集大成。",img:wm("%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg")},
  {title:"宫娥",artist:"迭戈·委拉斯开兹",year:"1656",era:"巴洛克",medium:"布面油画",country:"西班牙",location:"马德里普拉多博物馆",desc:"对观看与被观看关系的复杂思辨，画家本人也入画。",img:wm("Las_Meninas_01.jpg")},
  {title:"神奈川冲浪里",artist:"葛饰北斋",year:"约1831",era:"浮世绘",medium:"木版画",country:"日本",location:"多家博物馆藏",desc:"《富岳三十六景》之一，巨浪与远处富士山的永恒对峙。",img:wm("Tsunami_by_hokusai_19th_century.jpg")},
  {title:"亚维农的少女",artist:"巴勃罗·毕加索",year:"1907",era:"立体主义",medium:"布面油画",country:"西班牙",location:"纽约现代艺术博物馆",desc:"立体主义的开山之作，破碎的形体与非洲面具式的脸庞。",img:wm("Les_Demoiselles_d%27Avignon.jpg")},
  {title:"吃土豆的人",artist:"文森特·梵高",year:"1885",era:"后印象派",medium:"布面油画",country:"荷兰",location:"阿姆斯特丹梵高博物馆",desc:"昏暗灯下的农家晚餐，梵高早期对底层人民的深切同情。",img:wm("Van-willem-vincent-gogh-die-kartoffelesser-03.jpg")},
  {title:"向日葵",artist:"文森特·梵高",year:"1888",era:"后印象派",medium:"布面油画",country:"荷兰",location:"伦敦国家美术馆",desc:"灿烂的黄色花束，梵高在阿尔勒迎接高更到来的喜悦之作。",img:wm("Vincent_Willem_van_Gogh_127.jpg")},
  {title:"草地上的午餐",artist:"爱德华·马奈",year:"1863",era:"现实主义",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"裸女与着衣男子的并置在沙龙引发轩然大波，现代绘画的宣言。",img:wm("Edouard_Manet_-_Le_D%C3%A9jeuner_sur_l%27herbe.jpg")},
  {title:"奥林匹亚",artist:"爱德华·马奈",year:"1863",era:"现实主义",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"直视观者的裸体高级妓女，挑战学院派的理想化女性裸像。",img:wm("Edouard_Manet_-_Olympia_-_Google_Art_Project_3.jpg")},
  {title:"圣维克多山",artist:"保罗·塞尚",year:"约1904",era:"后印象派",medium:"布面油画",country:"法国",location:"费城艺术博物馆",desc:"塞尚反复描绘的故乡之山，以几何化笔触预示了立体主义。",img:wm("Paul_C%C3%A9zanne_-_Mont_Sainte-Victoire_-_Google_Art_Project.jpg")},
  {title:"舞蹈",artist:"亨利·马蒂斯",year:"1910",era:"野兽派",medium:"布面油画",country:"法国",location:"圣彼得堡冬宫博物馆",desc:"五个手拉手旋转的裸体，原始的生命律动与纯粹的色彩。",img:wm("Matisse-Dance_(I).jpg")},
  {title:"红黄蓝的构成",artist:"皮特·蒙德里安",year:"1930",era:"风格派",medium:"布面油画",country:"荷兰",location:"苏黎世美术馆",desc:"以黑色网格与三原色构筑的纯粹抽象秩序。",img:wm("Piet_Mondriaan,_1930_-_Mondrian_Composition_II_in_Red,_Blue,_and_Yellow.jpg")},
  {title:"持续性记忆",artist:"瓦西里·康定斯基",year:"1913",era:"抽象艺术",medium:"布面油画",country:"俄罗斯",location:"多家博物馆藏",desc:"康定斯基以色彩与线条的「内在必然性」开创纯粹抽象。",img:wm("Vassily_Kandinsky,_1913_-_Composition_7.jpg")},
  {title:"格兰德渡口",artist:"乔治·修拉",year:"1888",era:"后印象派",medium:"布面油画",country:"法国",location:"印第安纳波利斯艺术博物馆",desc:"点彩技法描绘的港口黄昏，宁静而富有诗意。",img:wm("Georges_Seurat_-_Le_Chenal_de_Gravelines,_Grand_Fort-Philippe.jpg")},
  {title:"埃及艳后",artist:"老卢卡斯·克拉纳赫",year:"约1530",era:"北方文艺复兴",medium:"木板油画",country:"德国",location:"私人收藏",desc:"克拉纳赫笔下纤细优雅的女性形象，北方文艺复兴的代表。",img:null},
  {title:"加拉太的凯旋",artist:"拉斐尔",year:"约1514",era:"文艺复兴",medium:"湿壁画",country:"意大利",location:"罗马法尔内西纳别墅",desc:"海中仙女加拉太驾驭海豚战车，盛期文艺复兴的优雅典范。",img:wm("Galatea_by_Raphael.jpg")},
  {title:"哀悼基督",artist:"米开朗基罗",year:"1498–1499",era:"文艺复兴",medium:"大理石雕塑",country:"意大利",location:"梵蒂冈圣彼得大教堂",desc:"圣母怀抱基督遗体，年轻的米开朗基罗成名之作，悲悯而宁静。",img:wm("Michelangelo%27s_Pieta_5450_cropncleaned_edit.jpg")},
  {title:"大卫",artist:"米开朗基罗",year:"1501–1504",era:"文艺复兴",medium:"大理石雕塑",country:"意大利",location:"佛罗伦萨学院美术馆",desc:"迎战歌利亚前蓄势的青年大卫，文艺复兴人体理想的化身。",img:wm("Michelangelo%27s_David_-_right_view_2.jpg")},
  {title:"维特鲁威人",artist:"列奥纳多·达·芬奇",year:"约1490",era:"文艺复兴",medium:"纸本钢笔淡彩",country:"意大利",location:"威尼斯学院美术馆",desc:"人体比例与几何的完美结合，文艺复兴科学与艺术合一的象征。",img:wm("Da_Vinci_Vitruve_Luc_Viatour.jpg")},
  {title:"最后的晚餐",artist:"列奥纳多·达·芬奇",year:"1495–1498",era:"文艺复兴",medium:"灰泥蛋彩壁画",country:"意大利",location:"米兰圣母恩宠教堂",desc:"基督宣告将被门徒出卖的瞬间，十二门徒各异的反应构成戏剧高潮。",img:wm("%C3%9Altima_Cena_-_Da_Vinci_5.jpg")},
  {title:"花神",artist:"提香",year:"约1515",era:"文艺复兴",medium:"布面油画",country:"意大利",location:"佛罗伦萨乌菲齐美术馆",desc:"威尼斯画派对女性肉体之美与丰饶的颂歌。",img:wm("Tizian_009.jpg")},
  {title:"乌尔比诺的维纳斯",artist:"提香",year:"1538",era:"文艺复兴",medium:"布面油画",country:"意大利",location:"佛罗伦萨乌菲齐美术馆",desc:"斜倚的裸体维纳斯，影响了后世马奈《奥林匹亚》。",img:wm("Tiziano_-_Venere_di_Urbino_-_Google_Art_Project.jpg")},
  {title:"人间乐园",artist:"耶罗尼米斯·博斯",year:"约1500",era:"北方文艺复兴",medium:"木板油画",country:"荷兰",location:"马德里普拉多博物馆",desc:"三联画展现从伊甸园到地狱的奇诡幻象，充满超现实的象征。",img:wm("The_Garden_of_earthly_delights.jpg")},
  {title:"阿尔诺芬尼夫妇像",artist:"扬·凡·艾克",year:"1434",era:"北方文艺复兴",medium:"木板油画",country:"佛兰德斯",location:"伦敦国家美术馆",desc:"细节精密的室内双人像，凸面镜中映出画家本人。",img:wm("Van_Eyck_-_Arnolfini_Portrait.jpg")},
  {title:"根特祭坛画",artist:"扬·凡·艾克",year:"1432",era:"北方文艺复兴",medium:"木板油画",country:"佛兰德斯",location:"根特圣巴夫主教座堂",desc:"早期尼德兰绘画的丰碑，油画技法的革命性成就。",img:wm("Lamgods_open.jpg")},
  {title:"狩猎者归来",artist:"老彼得·勃鲁盖尔",year:"1565",era:"北方文艺复兴",medium:"木板油画",country:"佛兰德斯",location:"维也纳艺术史博物馆",desc:"冬日雪景中归来的猎人，尼德兰风俗与风景画的杰作。",img:wm("Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_(Winter)_-_Google_Art_Project.jpg")},
  {title:"巴别塔",artist:"老彼得·勃鲁盖尔",year:"1563",era:"北方文艺复兴",medium:"木板油画",country:"佛兰德斯",location:"维也纳艺术史博物馆",desc:"宏伟而注定崩塌的通天塔，对人类狂妄的寓言。",img:wm("Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_(Vienna)_-_Google_Art_Project_-_edited.jpg")},
  {title:"使节",artist:"小汉斯·荷尔拜因",year:"1533",era:"北方文艺复兴",medium:"木板油画",country:"德国",location:"伦敦国家美术馆",desc:"双人全身像下方藏有著名的变形骷髅，暗喻死亡。",img:wm("Hans_Holbein_the_Younger_-_The_Ambassadors_-_Google_Art_Project.jpg")},
  {title:"杜普医生的解剖课",artist:"伦勃朗·范·莱因",year:"1632",era:"巴洛克",medium:"布面油画",country:"荷兰",location:"海牙莫瑞泰斯皇家美术馆",desc:"群像构图的革新，众人凝视解剖的专注神情。",img:wm("Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg")},
  {title:"基督下十字架",artist:"彼得·保罗·鲁本斯",year:"1612–1614",era:"巴洛克",medium:"木板油画",country:"佛兰德斯",location:"安特卫普圣母主教座堂",desc:"巴洛克式的动感与激情，对角线构图充满张力。",img:wm("0_La_Descente_de_Croix_-_P.P._Rubens_(Anvers).JPG")},
  {title:"圣马太蒙召",artist:"卡拉瓦乔",year:"1599–1600",era:"巴洛克",medium:"布面油画",country:"意大利",location:"罗马圣王路易堂",desc:"一束神光划破黑暗，明暗对照法（tenebrism）的典范。",img:wm("The_Calling_of_Saint_Matthew-Caravaggio_(1599-1600).jpg")},
  {title:"犹滴斩首荷罗孚尼",artist:"阿尔泰米西娅·真蒂莱斯基",year:"约1620",era:"巴洛克",medium:"布面油画",country:"意大利",location:"佛罗伦萨乌菲齐美术馆",desc:"女性力量的暴烈呈现，巴洛克明暗法的强烈戏剧性。",img:wm("Artemisia_Gentileschi_-_Judith_Beheading_Holofernes_-_WGA8563.jpg")},
  {title:"倒牛奶的女仆",artist:"约翰内斯·维米尔",year:"约1658",era:"巴洛克",medium:"布面油画",country:"荷兰",location:"阿姆斯特丹国立博物馆",desc:"宁静的日常瞬间被赋予近乎神圣的光辉。",img:wm("Johannes_Vermeer_-_Het_melkmeisje_-_Google_Art_Project.jpg")},
  {title:"戴尔夫特一景",artist:"约翰内斯·维米尔",year:"约1660–1661",era:"巴洛克",medium:"布面油画",country:"荷兰",location:"海牙莫瑞泰斯皇家美术馆",desc:"被誉为最美的城市风景画，光影下的故乡戴尔夫特。",img:wm("Vermeer-view-of-delft.jpg")},
  {title:"查理一世骑马像",artist:"安东尼·凡·戴克",year:"约1637–1638",era:"巴洛克",medium:"布面油画",country:"佛兰德斯",location:"伦敦国家美术馆",desc:"英王查理一世的庄严骑像，巴洛克宫廷肖像的典范。",img:wm("Sir_Anthony_Van_Dyck_-_Charles_I_(1600-49)_-_Google_Art_Project.jpg")},
  {title:"圣特蕾莎的狂喜",artist:"济安·贝尼尼",year:"1647–1652",era:"巴洛克",medium:"大理石雕塑",country:"意大利",location:"罗马胜利之后圣母堂",desc:"天使之箭刺入圣女心房的灵性狂喜，巴洛克雕塑巅峰。",img:wm("Ecstasy_of_Saint_Teresa_September_2015-2a.jpg")},
  {title:"普罗塞庇娜的劫掠",artist:"济安·贝尼尼",year:"1621–1622",era:"巴洛克",medium:"大理石雕塑",country:"意大利",location:"罗马博尔盖塞美术馆",desc:"冥王手指陷入少女肌肤的逼真触感，大理石被赋予血肉。",img:wm("Rape_of_Proserpina_September_2015-1a.jpg")},
  {title:"秋千",artist:"让-奥诺雷·弗拉戈纳尔",year:"1767",era:"洛可可",medium:"布面油画",country:"法国",location:"伦敦华莱士收藏馆",desc:"洛可可式的轻佻欢愉，荡秋千少女飞起的鞋子。",img:wm("Jean-Honor%C3%A9_Fragonard_-_The_Swing_-_WGA08051.jpg")},
  {title:"舟发西苔岛",artist:"安托万·华托",year:"1717",era:"洛可可",medium:"布面油画",country:"法国",location:"巴黎卢浮宫",desc:"恋人们前往爱之岛的优雅游乐，华托独创的「雅宴」题材。",img:wm("L%27Embarquement_pour_Cythere,_by_Antoine_Watteau,_from_C2RMF_retouched.jpg")},
  {title:"马拉之死",artist:"雅克-路易·大卫",year:"1793",era:"新古典主义",medium:"布面油画",country:"法国",location:"布鲁塞尔比利时皇家美术馆",desc:"革命者马拉遇刺浴中，新古典主义的政治殉道图像。",img:wm("Death_of_Marat_by_David.jpg")},
  {title:"贺拉斯兄弟之誓",artist:"雅克-路易·大卫",year:"1784",era:"新古典主义",medium:"布面油画",country:"法国",location:"巴黎卢浮宫",desc:"为国宣誓的英雄气概，新古典主义的道德典范。",img:wm("Jacques-Louis_David,_Le_Serment_des_Horaces.jpg")},
  {title:"拿破仑加冕",artist:"雅克-路易·大卫",year:"1805–1807",era:"新古典主义",medium:"布面油画",country:"法国",location:"巴黎卢浮宫",desc:"宏大的加冕典礼场面，拿破仑权力的视觉颂歌。",img:wm("Jacques-Louis_David_-_The_Coronation_of_Napoleon_(1805-1807).jpg")},
  {title:"大宫女",artist:"让·奥古斯特·多米尼克·安格尔",year:"1814",era:"新古典主义",medium:"布面油画",country:"法国",location:"巴黎卢浮宫",desc:"刻意拉长的背部曲线，对古典理想美的优雅扭曲。",img:wm("Jean_Auguste_Dominique_Ingres,_La_Grande_Odalisque,_1814.jpg")},
  {title:"1808年5月3日",artist:"弗朗西斯科·戈雅",year:"1814",era:"浪漫主义",medium:"布面油画",country:"西班牙",location:"马德里普拉多博物馆",desc:"法军枪决西班牙起义者，对战争暴行的悲愤控诉。",img:wm("El_Tres_de_Mayo,_by_Francisco_de_Goya,_from_Prado_thin_black_margin.jpg")},
  {title:"农神吞噬其子",artist:"弗朗西斯科·戈雅",year:"约1819–1823",era:"浪漫主义",medium:"湿壁画转移布面",country:"西班牙",location:"马德里普拉多博物馆",desc:"「黑色绘画」之一，疯狂吞食亲子的恐怖图景。",img:wm("Francisco_de_Goya,_Saturno_devorando_a_su_hijo_(1819-1823).jpg")},
  {title:"梅杜萨之筏",artist:"泰奥多尔·籍里柯",year:"1818–1819",era:"浪漫主义",medium:"布面油画",country:"法国",location:"巴黎卢浮宫",desc:"海难幸存者绝望挣扎的宏大场面，浪漫主义的悲剧张力。",img:wm("JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_La_Balsa_de_la_Medusa_(Museo_del_Louvre,_1818-19).jpg")},
  {title:"雾海上的旅人",artist:"卡斯帕·大卫·弗里德里希",year:"约1818",era:"浪漫主义",medium:"布面油画",country:"德国",location:"汉堡美术馆",desc:"背对观者的旅人凝视云海，浪漫主义崇高感的象征。",img:wm("Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg")},
  {title:"奴隶船",artist:"约瑟夫·透纳",year:"1840",era:"浪漫主义",medium:"布面油画",country:"英国",location:"波士顿美术馆",desc:"暴风雨海面的炽烈色彩，对奴隶贸易暴行的控诉。",img:wm("Slave-ship.jpg")},
  {title:"雨、蒸汽和速度",artist:"约瑟夫·透纳",year:"1844",era:"浪漫主义",medium:"布面油画",country:"英国",location:"伦敦国家美术馆",desc:"疾驰的蒸汽火车融入光与雾，预示了印象派。",img:wm("Turner_-_Rain,_Steam_and_Speed_-_National_Gallery_file.jpg")},
  {title:"干草车",artist:"约翰·康斯太勃尔",year:"1821",era:"浪漫主义",medium:"布面油画",country:"英国",location:"伦敦国家美术馆",desc:"英格兰田园的宁静诗意，自然光影的真挚描绘。",img:wm("John_Constable_The_Hay_Wain.jpg")},
  {title:"奥南的葬礼",artist:"古斯塔夫·库尔贝",year:"1849–1850",era:"现实主义",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"以历史画的尺幅描绘平民葬礼，现实主义的宣言。",img:wm("Gustave_Courbet_-_A_Burial_at_Ornans_-_Google_Art_Project_2.jpg")},
  {title:"画室",artist:"古斯塔夫·库尔贝",year:"1855",era:"现实主义",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"画家以「真实的寓言」概括其艺术生涯的七年。",img:wm("Gustave_Courbet_-_The_Artist%27s_Studio_-_Google_Art_Project_2.jpg")},
  {title:"奥菲莉娅",artist:"约翰·埃弗里特·米莱",year:"1851–1852",era:"拉斐尔前派",medium:"布面油画",country:"英国",location:"伦敦泰特美术馆",desc:"溺水的奥菲莉娅漂浮于繁花溪流，细节精微的悲剧之美。",img:wm("John_Everett_Millais_-_Ophelia_-_Google_Art_Project.jpg")},
  {title:"普罗塞庇娜",artist:"但丁·加百列·罗塞蒂",year:"1874",era:"拉斐尔前派",medium:"布面油画",country:"英国",location:"伦敦泰特美术馆",desc:"手持石榴的冥后，拉斐尔前派理想化女性之美。",img:wm("Dante_Gabriel_Rossetti_-_Proserpine_-_Google_Art_Project.jpg")},
  {title:"芭蕾舞课",artist:"埃德加·德加",year:"1873–1876",era:"印象派",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"德加对舞者排练瞬间的捕捉，构图新颖如摄影快照。",img:wm("Edgar_Degas_-_The_Ballet_Class_-_Google_Art_Project.jpg")},
  {title:"煎饼磨坊的舞会",artist:"皮埃尔-奥古斯特·雷诺阿",year:"1876",era:"印象派",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"蒙马特露天舞会的斑驳阳光与欢愉，印象派的生活礼赞。",img:wm("Pierre-Auguste_Renoir,_Le_Moulin_de_la_Galette.jpg")},
  {title:"船上的午宴",artist:"皮埃尔-奥古斯特·雷诺阿",year:"1880–1881",era:"印象派",medium:"布面油画",country:"法国",location:"华盛顿菲利普斯收藏馆",desc:"塞纳河畔友人聚餐的明媚时光，光色与人情的交融。",img:wm("Pierre-Auguste_Renoir_-_Luncheon_of_the_Boating_Party_-_Google_Art_Project.jpg")},
  {title:"圣拉扎尔火车站",artist:"克劳德·莫奈",year:"1877",era:"印象派",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"蒸汽弥漫的现代车站，工业时代的印象派诗篇。",img:wm("Claude_Monet_-_Arrival_of_the_Normandy_Train,_Gare_Saint-Lazare_-_Google_Art_Project.jpg")},
  {title:"鲁昂大教堂",artist:"克劳德·莫奈",year:"1894",era:"印象派",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"同一教堂在不同光线下的系列描绘，光的研究。",img:wm("Claude_Monet_-_Rouen_Cathedral,_Facade_(Sunset).jpg")},
  {title:"阿尔的卧室",artist:"文森特·梵高",year:"1888",era:"后印象派",medium:"布面油画",country:"荷兰",location:"阿姆斯特丹梵高博物馆",desc:"梵高在黄房子里的卧室，质朴色彩中的安宁渴望。",img:wm("Vincent_van_Gogh_-_De_slaapkamer_-_Google_Art_Project.jpg")},
  {title:"夜间咖啡馆露台",artist:"文森特·梵高",year:"1888",era:"后印象派",medium:"布面油画",country:"荷兰",location:"奥特洛克勒勒-米勒博物馆",desc:"阿尔星空下的咖啡馆，温暖的黄与深邃的蓝交织。",img:wm("Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_(Yorck).jpg")},
  {title:"自画像",artist:"文森特·梵高",year:"1889",era:"后印象派",medium:"布面油画",country:"荷兰",location:"巴黎奥赛博物馆",desc:"漩涡背景中凝视的梵高，内心动荡的真实写照。",img:wm("Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project_(454045).jpg")},
  {title:"我们从何处来？",artist:"保罗·高更",year:"1897–1898",era:"后印象派",medium:"布面油画",country:"法国",location:"波士顿美术馆",desc:"高更在塔希提的哲思巨作，对生命起源与归宿的追问。",img:wm("Paul_Gauguin_-_D%27ou_venons-nous.jpg")},
  {title:"黄色基督",artist:"保罗·高更",year:"1889",era:"后印象派",medium:"布面油画",country:"法国",location:"水牛城奥尔布赖特-诺克斯美术馆",desc:"布列塔尼乡村的钉刑场景，平涂色块与象征主义。",img:wm("Paul_Gauguin_-_The_Yellow_Christ_-_Google_Art_Project.jpg")},
  {title:"玩纸牌的人",artist:"保罗·塞尚",year:"1890–1895",era:"后印象派",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"专注牌局的农人，几何化的构图与厚重的体量感。",img:wm("Les_joueurs_de_carte,_par_Paul_C%C3%A9zanne.jpg")},
  {title:"苹果与橙子",artist:"保罗·塞尚",year:"约1899",era:"后印象派",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"打破单一视点的静物革命，现代绘画之父的探索。",img:wm("Paul_C%C3%A9zanne,_Still_Life_with_Apples_and_Oranges.jpg")},
  {title:"红磨坊",artist:"亨利·德·图卢兹-劳特累克",year:"1892–1895",era:"后印象派",medium:"布面油画",country:"法国",location:"芝加哥艺术博物馆",desc:"巴黎夜生活的浮华与孤寂，海报式的大胆构图。",img:wm("Henri_de_Toulouse-Lautrec_005.jpg")},
  {title:"生命之舞",artist:"爱德华·蒙克",year:"1899–1900",era:"象征主义",medium:"布面油画",country:"挪威",location:"奥斯陆国家美术馆",desc:"从纯真到衰老的生命之舞，对爱与死的象征性沉思。",img:wm("Edvard_Munch_-_The_Dance_of_Life_(1899-1900).jpg")},
  {title:"青春期",artist:"爱德华·蒙克",year:"1894–1895",era:"象征主义",medium:"布面油画",country:"挪威",location:"奥斯陆国家美术馆",desc:"少女初临青春的不安，巨大阴影暗示心理的恐惧。",img:wm("Edvard_Munch_-_Puberty_-_Google_Art_Project.jpg")},
  {title:"达娜厄",artist:"古斯塔夫·克里姆特",year:"1907",era:"象征主义",medium:"布面油画",country:"奥地利",location:"维也纳私人收藏",desc:"宙斯化作金雨降临达娜厄，情欲与黄金的交融。",img:wm("Gustav_Klimt_010.jpg")},
  {title:"阿黛尔·布洛赫-鲍尔肖像一号",artist:"古斯塔夫·克里姆特",year:"1907",era:"象征主义",medium:"布面油画与金银箔",country:"奥地利",location:"纽约新美术馆",desc:"「金色阿黛尔」，奥地利的蒙娜丽莎，金箔肖像巅峰。",img:wm("Gustav_Klimt_046.jpg")},
  {title:"戴帽子的女人",artist:"亨利·马蒂斯",year:"1905",era:"野兽派",medium:"布面油画",country:"法国",location:"旧金山现代艺术博物馆",desc:"狂野的非自然色彩，野兽派引发争议的开端之作。",img:wm("Matisse-Woman-with-a-Hat.jpg")},
  {title:"生活的欢乐",artist:"亨利·马蒂斯",year:"1905–1906",era:"野兽派",medium:"布面油画",country:"法国",location:"费城巴恩斯基金会",desc:"田园牧歌式的裸体群像，纯色与曲线的感官愉悦。",img:wm("Henri_Matisse,_1906,_Le_bonheur_de_vivre.jpg")},
  {title:"红色画室",artist:"亨利·马蒂斯",year:"1911",era:"野兽派",medium:"布面油画",country:"法国",location:"纽约现代艺术博物馆",desc:"整个画室浸入炽烈的红，空间被色彩消解。",img:wm("Henri_Matisse,_1911,_The_Red_Studio,_oil_on_canvas,_181_x_219.1_cm,_Museum_of_Modern_Art.jpg")},
  {title:"格特鲁德·斯泰因肖像",artist:"巴勃罗·毕加索",year:"1905–1906",era:"立体主义",medium:"布面油画",country:"西班牙",location:"纽约大都会艺术博物馆",desc:"面具般的脸庞预示立体主义，作家斯泰因的肖像。",img:wm("Pablo_Picasso,_1906,_Portrait_of_Gertrude_Stein,_Metropolitan_Museum_of_Art,_New_York.jpg")},
  {title:"三个乐师",artist:"巴勃罗·毕加索",year:"1921",era:"立体主义",medium:"布面油画",country:"西班牙",location:"纽约现代艺术博物馆",desc:"综合立体主义的代表，鲜明色块拼贴出的乐师。",img:wm("Pablo_Picasso,_1921,_Nous_autres_musiciens_(Three_Musicians),_oil_on_canvas,_204.5_x_188.3_cm,_Philadelphia_Museum_of_Art.jpg")},
  {title:"哭泣的女人",artist:"巴勃罗·毕加索",year:"1937",era:"立体主义",medium:"布面油画",country:"西班牙",location:"伦敦泰特美术馆",desc:"破碎扭曲的悲伤面容，与《格尔尼卡》同期的苦难图像。",img:wm("Pablo_Picasso,_1937,_Weeping_Woman_(La_Femme_qui_pleure),_oil_on_canvas,_60_x_49_cm,_Tate_Modern,_London.jpg")},
  {title:"梦",artist:"巴勃罗·毕加索",year:"1932",era:"立体主义",medium:"布面油画",country:"西班牙",location:"私人收藏",desc:"沉睡情人玛丽-泰蕾兹的柔美曲线，色彩明丽。",img:null},
  {title:"白上之白",artist:"卡济米尔·马列维奇",year:"1918",era:"至上主义",medium:"布面油画",country:"俄罗斯",location:"纽约现代艺术博物馆",desc:"白色方块叠于白底，抽象艺术的极致简化。",img:wm("Suprematist_Composition_-_White_on_White_-_Kazimir_Malevich.jpg")},
  {title:"黑方块",artist:"卡济米尔·马列维奇",year:"1915",era:"至上主义",medium:"布面油画",country:"俄罗斯",location:"莫斯科特列季亚科夫画廊",desc:"绘画的「零点」，至上主义宣言式的纯粹几何。",img:wm("Kazimir_Malevich,_1915,_Black_Suprematic_Square,_oil_on_linen_canvas,_79.5_x_79.5_cm,_Tretyakov_Gallery,_Moscow.jpg")},
  {title:"红色的和谐",artist:"亨利·马蒂斯",year:"1908",era:"野兽派",medium:"布面油画",country:"法国",location:"圣彼得堡冬宫博物馆",desc:"装饰性平面与蓝色藤蔓纹样，色彩主导的室内。",img:wm("Matisse_-_The_Dessert_Harmony_in_Red.jpg")},
  {title:"百老汇爵士乐",artist:"皮特·蒙德里安",year:"1942–1943",era:"风格派",medium:"布面油画",country:"荷兰",location:"纽约现代艺术博物馆",desc:"跳动的彩色方块如爵士节奏，蒙德里安的纽约礼赞。",img:wm("Piet_Mondrian,_1942_-_Broadway_Boogie_Woogie.jpg")},
  {title:"喷泉",artist:"马塞尔·杜尚",year:"1917",era:"达达主义",medium:"现成品（小便池）",country:"法国",location:"多处复制品",desc:"署名「R.Mutt」的小便池，颠覆了艺术的定义。",img:wm("Marcel_Duchamp,_1917,_Fountain,_photograph_by_Alfred_Stieglitz.jpg")},
  {title:"下楼梯的裸女二号",artist:"马塞尔·杜尚",year:"1912",era:"立体主义",medium:"布面油画",country:"法国",location:"费城艺术博物馆",desc:"将运动分解为连续形态，立体主义与未来主义的融合。",img:wm("Duchamp_-_Nude_Descending_a_Staircase.jpg")},
  {title:"我与村庄",artist:"马克·夏加尔",year:"1911",era:"超现实主义",medium:"布面油画",country:"白俄罗斯",location:"纽约现代艺术博物馆",desc:"梦幻的故乡记忆，人与动物的诗意并置。",img:wm("Marc_Chagall,_1911,_I_and_the_Village,_oil_on_canvas,_192.1_x_151.4_cm,_Museum_of_Modern_Art,_New_York.jpg")},
  {title:"生日",artist:"马克·夏加尔",year:"1915",era:"超现实主义",medium:"纸板油画",country:"白俄罗斯",location:"纽约现代艺术博物馆",desc:"飘浮空中的热吻，爱情让恋人失重飞翔。",img:wm("Marc_Chagall,_1915,_Birthday_(L%27Anniversaire),_oil_on_cardboard,_80.6_x_99.7_cm,_Museum_of_Modern_Art,_New_York.jpg")},
  {title:"持续的记忆",artist:"乔治·德·基里科",year:"1914",era:"形而上画派",medium:"布面油画",country:"意大利",location:"私人收藏",desc:"空寂广场与长影，形而上画派的忧郁与梦境感。",img:wm("Giorgio_de_Chirico,_1913,_The_Uncertainty_of_the_Poet.jpg")},
  {title:"红气球",artist:"保罗·克利",year:"1922",era:"包豪斯",medium:"纱布油画",country:"瑞士",location:"纽约古根海姆博物馆",desc:"几何形与色块构成的诗意都市，童真与精密并存。",img:wm("Paul_Klee,_Red_Balloon,_1922.jpg")},
  {title:"喧闹的机器",artist:"保罗·克利",year:"1922",era:"包豪斯",medium:"水彩与油转印",country:"瑞士",location:"纽约现代艺术博物馆",desc:"歌唱的机械小鸟，对机器时代的幽默讽喻。",img:wm("Twittering_Machine.jpg")},
  {title:"加泰罗尼亚风景",artist:"胡安·米罗",year:"1923–1924",era:"超现实主义",medium:"布面油画",country:"西班牙",location:"纽约现代艺术博物馆",desc:"符号化的奇幻生物漂浮于黄色大地，米罗的诗意宇宙。",img:wm("Joan_Mir%C3%B3,_1923-24,_The_Tilled_Field,_oil_on_canvas,_66_x_92.7_cm,_Solomon_R._Guggenheim_Museum,_New_York.jpg")},
  {title:"人子",artist:"勒内·马格利特",year:"1964",era:"超现实主义",medium:"布面油画",country:"比利时",location:"私人收藏",desc:"礼帽绅士的脸被青苹果遮挡，对可见与隐藏的诘问。",img:wm("Magritte_TheSonOfMan.jpg")},
  {title:"形象的叛逆",artist:"勒内·马格利特",year:"1929",era:"超现实主义",medium:"布面油画",country:"比利时",location:"洛杉矶郡艺术博物馆",desc:"「这不是一只烟斗」，对图像与现实关系的哲学游戏。",img:wm("MagrittePipe.jpg")},
  {title:"两个弗里达",artist:"弗里达·卡罗",year:"1939",era:"超现实主义",medium:"布面油画",country:"墨西哥",location:"墨西哥城现代艺术博物馆",desc:"两个自我相连的心脏与血管，身份与痛苦的双重自画像。",img:wm("Las_dos_Fridas.jpg")},
  {title:"破碎的脊柱",artist:"弗里达·卡罗",year:"1944",era:"超现实主义",medium:"纤维板油画",country:"墨西哥",location:"墨西哥城多洛雷斯·奥尔梅多博物馆",desc:"以钉满身体的自画像表达车祸后的剧痛与坚韧。",img:null},
  {title:"内战的预兆",artist:"萨尔瓦多·达利",year:"1936",era:"超现实主义",medium:"布面油画",country:"西班牙",location:"费城艺术博物馆",desc:"自相撕扯的巨大躯体，对西班牙内战的超现实预言。",img:wm("Soft_Construction_with_Boiled_Beans_(Premonition_of_Civil_War).jpg")},
  {title:"睡眠",artist:"萨尔瓦多·达利",year:"1937",era:"超现实主义",medium:"布面油画",country:"西班牙",location:"私人收藏",desc:"由细拐杖支撑的巨大头颅，梦与现实的脆弱平衡。",img:null},
  {title:"夜鹰",artist:"爱德华·霍珀",year:"1942",era:"美国现实主义",medium:"布面油画",country:"美国",location:"芝加哥艺术博物馆",desc:"深夜餐馆中孤独的都市人，美国式疏离感的经典图像。",img:wm("Nighthawks_by_Edward_Hopper_1942.jpg")},
  {title:"铁路旁的房子",artist:"爱德华·霍珀",year:"1925",era:"美国现实主义",medium:"布面油画",country:"美国",location:"纽约现代艺术博物馆",desc:"铁轨旁孤立的维多利亚式宅邸，荒凉而疏离。",img:wm("Edward_Hopper_House_by_the_Railroad_1925.jpg")},
  {title:"克里斯蒂娜的世界",artist:"安德鲁·怀斯",year:"1948",era:"美国现实主义",medium:"蛋彩画",country:"美国",location:"纽约现代艺术博物馆",desc:"残疾女子匍匐于草坡望向远处农舍，孤独与渴望。",img:wm("Christinas_World.jpg")},
  {title:"一号，1950（薰衣草之雾）",artist:"杰克逊·波洛克",year:"1950",era:"抽象表现主义",medium:"布面油彩与瓷漆",country:"美国",location:"华盛顿国家美术馆",desc:"滴洒技法编织的能量之网，行动绘画的巅峰。",img:wm("Jackson_Pollock,_1950,_Autumn_Rhythm_(Number_30),_Metropolitan_Museum_of_Art.jpg")},
  {title:"秋韵（三十号）",artist:"杰克逊·波洛克",year:"1950",era:"抽象表现主义",medium:"布面瓷漆",country:"美国",location:"纽约大都会艺术博物馆",desc:"棕黑线条的律动如秋日韵律，滴画的纯粹动能。",img:wm("Number_8,_1949_(Jackson_Pollock).jpg")},
  {title:"橙红黄",artist:"马克·罗斯科",year:"1961",era:"色域绘画",medium:"布面油画",country:"美国",location:"私人收藏",desc:"漂浮的矩形色块，引人沉思的崇高色彩体验。",img:wm("No._61_(Rust_and_Blue)_Mark_Rothko_1953.jpg")},
  {title:"玛丽莲·梦露双联画",artist:"安迪·沃霍尔",year:"1962",era:"波普艺术",medium:"布面丝网印刷",country:"美国",location:"伦敦泰特美术馆",desc:"重复印刷的梦露形象，名人崇拜与大众消费的图腾。",img:wm("Marilyn_Diptych.jpg")},
  {title:"金宝汤罐头",artist:"安迪·沃霍尔",year:"1962",era:"波普艺术",medium:"布面合成聚合物",country:"美国",location:"纽约现代艺术博物馆",desc:"三十二罐汤的并置，消费社会的冷峻肖像。",img:wm("Campbells_Soup_Cans_MOMA.jpg")},
  {title:"哭泣的女孩",artist:"罗伊·利希滕斯坦",year:"1964",era:"波普艺术",medium:"瓷漆钢板",country:"美国",location:"私人收藏",desc:"放大的漫画分格与本戴点，波普艺术的商业图像挪用。",img:wm("Roy_Lichtenstein_Drowning_Girl.jpg")},
  {title:"国旗",artist:"贾斯培·琼斯",year:"1954–1955",era:"新达达主义",medium:"布面蜡画拼贴",country:"美国",location:"纽约现代艺术博物馆",desc:"以蜡画重绘美国国旗，对符号与物性的追问。",img:wm("Flag_by_Jasper_Johns_1954-55.jpg")},
  {title:"气球女孩",artist:"班克斯",year:"2002",era:"街头艺术",medium:"喷漆模板",country:"英国",location:"多处墙面",desc:"伸手追逐红气球的女孩，希望与失去的当代寓言。",img:null},
  {title:"思想者",artist:"奥古斯特·罗丹",year:"1904",era:"现代雕塑",medium:"青铜",country:"法国",location:"巴黎罗丹博物馆",desc:"沉思中的裸体男子，对人类理智与痛苦的凝缩。",img:wm("The_Thinker,_Rodin.jpg")},
  {title:"加莱义民",artist:"奥古斯特·罗丹",year:"1884–1889",era:"现代雕塑",medium:"青铜",country:"法国",location:"加莱及多处",desc:"六位赴死市民的群像，对牺牲与人性的深刻刻画。",img:wm("Burghers_of_Calais,_Rodin,_Calais,_France.jpg")},
  {title:"吻",artist:"奥古斯特·罗丹",year:"1882",era:"现代雕塑",medium:"大理石",country:"法国",location:"巴黎罗丹博物馆",desc:"相拥热吻的恋人，情感与肉体之美的颂歌。",img:wm("Rodin_-_Le_Baiser_06.jpg")},
  {title:"空间中连续的独特形体",artist:"翁贝托·波丘尼",year:"1913",era:"未来主义",medium:"青铜",country:"意大利",location:"多家博物馆藏",desc:"疾行人体的动态形体，未来主义对速度的礼赞。",img:wm("%27Unique_Forms_of_Continuity_in_Space%27,_1913_bronze_by_Umberto_Boccioni.jpg")},
  {title:"吻（雕塑）",artist:"康斯坦丁·布朗库西",year:"1907–1908",era:"现代雕塑",medium:"石灰石",country:"罗马尼亚",location:"克拉约瓦艺术博物馆",desc:"两个相拥形体的极简抽象，对罗丹《吻》的回应。",img:null},
  {title:"图坦卡蒙黄金面具",artist:"古埃及匠师",year:"约公元前1323年",era:"古埃及",medium:"黄金与宝石",country:"埃及",location:"开罗埃及博物馆",desc:"少年法老的黄金葬礼面具，古埃及工艺的极致。",img:wm("CairoEgMuseumTaaMaskMostlyPhotographed.jpg")},
  {title:"奈费尔提蒂半身像",artist:"图特摩斯",year:"约公元前1345年",era:"古埃及",medium:"石灰岩与灰泥彩绘",country:"埃及",location:"柏林新博物馆",desc:"古埃及王后的优雅头像，永恒的女性美典范。",img:wm("Nofretete_Neues_Museum.jpg")},
  {title:"米洛的维纳斯",artist:"安提俄克的亚历山德罗斯",year:"约公元前130–100年",era:"古希腊",medium:"大理石",country:"希腊",location:"巴黎卢浮宫",desc:"断臂的爱神维纳斯，希腊化时期理想美的化身。",img:wm("Venus_de_Milo_Louvre_Ma399_n4.jpg")},
  {title:"萨莫色雷斯的胜利女神",artist:"佚名",year:"约公元前190年",era:"古希腊",medium:"大理石",country:"希腊",location:"巴黎卢浮宫",desc:"展翅立于船头的胜利女神，衣袂飞扬的动感杰作。",img:wm("Nike_of_Samothrake_Louvre_Ma2369_n4.jpg")},
  {title:"掷铁饼者",artist:"米隆",year:"约公元前450年",era:"古希腊",medium:"大理石（罗马摹本）",country:"希腊",location:"罗马国立博物馆",desc:"投掷瞬间凝固的运动员，古典平衡与动势的典范。",img:wm("Discobolus_Townley_BM_GR1805.7-3.43.jpg")},
  {title:"拉奥孔与儿子",artist:"阿格桑德罗斯等",year:"约公元前27年",era:"古希腊",medium:"大理石",country:"希腊",location:"梵蒂冈博物馆",desc:"被巨蛇缠绕的祭司父子，希腊化雕塑的痛苦张力。",img:wm("Laocoon_Pio-Clementino_Inv1059-1064-1067.jpg")},
  {title:"兵马俑",artist:"秦代工匠",year:"约公元前210年",era:"中国秦代",medium:"陶",country:"中国",location:"西安秦始皇陵",desc:"守护始皇陵的千军万马，每尊面容各异的陶塑军团。",img:wm("Terracotta_Army,_View_of_Pit_1.jpg")},
  {title:"清明上河图",artist:"张择端",year:"约1100年",era:"中国宋代",medium:"绢本设色",country:"中国",location:"北京故宫博物院",desc:"北宋汴京的繁华长卷，五米画面尽收市井百态。",img:wm("Along_the_River_During_the_Qingming_Festival_(Qing_Court_Version).jpg")},
  {title:"富春山居图",artist:"黄公望",year:"1350",era:"中国元代",medium:"纸本水墨",country:"中国",location:"台北故宫博物院等",desc:"元代文人山水的巅峰，富春江两岸的萧散意境。",img:null},
  {title:"千里江山图",artist:"王希孟",year:"1113",era:"中国宋代",medium:"绢本青绿设色",country:"中国",location:"北京故宫博物院",desc:"十八岁少年所绘的青绿山水长卷，气势恢宏。",img:null},
  {title:"洛神赋图",artist:"顾恺之（宋摹）",year:"约4世纪",era:"中国魏晋",medium:"绢本设色",country:"中国",location:"北京故宫博物院等",desc:"以连续画面演绎曹植与洛神的浪漫传说。",img:null},
  {title:"韩熙载夜宴图",artist:"顾闳中",year:"约970年",era:"中国五代",medium:"绢本设色",country:"中国",location:"北京故宫博物院",desc:"分段描绘南唐重臣夜宴的奢华与隐忧。",img:null},
  {title:"敦煌飞天壁画",artist:"敦煌匠师",year:"4–14世纪",era:"中国佛教艺术",medium:"壁画",country:"中国",location:"甘肃敦煌莫高窟",desc:"飘带凌空的飞天形象，丝路佛教艺术的瑰宝。",img:null},
  {title:"乐山大佛",artist:"唐代匠师",year:"713–803",era:"中国唐代",medium:"石刻",country:"中国",location:"四川乐山",desc:"依崖凿成的弥勒坐佛，世界最大的石刻佛像。",img:wm("Leshan_Buddha_Statue_View.JPG")},
  {title:"波斯细密画·夜宴",artist:"波斯宫廷画师",year:"约15世纪",era:"伊斯兰艺术",medium:"纸本水粉",country:"波斯",location:"多家博物馆藏",desc:"精致繁复的细密画，伊斯兰书籍插图的华美传统。",img:null},
  {title:"泰姬陵",artist:"乌斯塔德·艾哈迈德",year:"1632–1653",era:"莫卧儿建筑",medium:"白色大理石建筑",country:"印度",location:"阿格拉",desc:"沙贾汗为爱妃所建的白色陵墓，建筑与爱情的不朽象征。",img:wm("Taj_Mahal_(Edited).jpeg")},
  {title:"持矛者",artist:"波留克列特斯",year:"约公元前440年",era:"古希腊",medium:"大理石（罗马摹本）",country:"希腊",location:"那不勒斯国立考古博物馆",desc:"体现「法则」（Canon）的理想人体比例。",img:wm("Doryphoros_MAN_Napoli_Inv6011-2.jpg")},
  {title:"拿破仑穿越阿尔卑斯山",artist:"雅克-路易·大卫",year:"1801",era:"新古典主义",medium:"布面油画",country:"法国",location:"马迈松城堡",desc:"骑跃骏马的英雄拿破仑，权力意志的浪漫化宣传。",img:wm("Jacques-Louis_David_-_Bonaparte_franchissant_le_Grand_Saint-Bernard,_20_mai_1800_-_Google_Art_Project.jpg")},
  {title:"土耳其浴室",artist:"让·奥古斯特·多米尼克·安格尔",year:"1862",era:"新古典主义",medium:"布面油画",country:"法国",location:"巴黎卢浮宫",desc:"圆形画框中群集的裸女，东方主义的官能幻想。",img:wm("Le_Bain_Turc,_by_Jean_Auguste_Dominique_Ingres,_from_C2RMF_retouched.jpg")},
  {title:"泉",artist:"让·奥古斯特·多米尼克·安格尔",year:"1856",era:"新古典主义",medium:"布面油画",country:"法国",location:"巴黎奥赛博物馆",desc:"手持水罐的纯洁裸女，新古典理想美的完成。",img:wm("Jean-Auguste-Dominique_Ingres_-_The_Spring_-_Google_Art_Project_2.jpg")},
  {title:"瓦平松的浴女",artist:"让·奥古斯特·多米尼克·安格尔",year:"1808",era:"新古典主义",medium:"布面油画",country:"法国",location:"巴黎卢浮宫",desc:"背对观者的浴女，光洁背脊的优雅曲线。",img:wm("Ingres,_The_Valpin%C3%A7on_Bather.jpg")},
  {title:"草垛",artist:"克劳德·莫奈",year:"1890–1891",era:"印象派",medium:"布面油画",country:"法国",location:"芝加哥艺术博物馆等",desc:"同一草垛在四季晨昏中的色彩变奏系列。",img:wm("Claude_Monet_-_Meule,_milieu_du_jour_%5BHaystack,_midday%5D,_1890.jpg")},
  {title:"威尼斯大运河",artist:"卡纳莱托",year:"约1730",era:"洛可可",medium:"布面油画",country:"意大利",location:"多家博物馆藏",desc:"精确如照片的威尼斯风景，「风景画」（veduta）巨匠。",img:wm("Canaletto_-_The_Grand_Canal_and_the_Church_of_the_Salute_-_Google_Art_Project.jpg")},
  {title:"蓝衣男孩",artist:"托马斯·庚斯博罗",year:"约1770",era:"洛可可",medium:"布面油画",country:"英国",location:"圣马力诺亨廷顿图书馆",desc:"身着蓝缎的少年肖像，英国肖像画的优雅典范。",img:wm("Thomas_Gainsborough_-_The_Blue_Boy_(The_Huntington_Library,_San_Marino_L._A.).jpg")},
  {title:"圣母领报",artist:"弗拉·安杰利科",year:"约1440–1445",era:"文艺复兴",medium:"湿壁画",country:"意大利",location:"佛罗伦萨圣马可修道院",desc:"天使向圣母报喜的静谧场景，早期文艺复兴的虔诚。",img:wm("ANGELICO,_Fra_Annunciation,_1437-46_(2236990916).jpg")},
  {title:"春",artist:"桑德罗·波提切利",year:"约1480",era:"文艺复兴",medium:"木板蛋彩",country:"意大利",location:"佛罗伦萨乌菲齐美术馆",desc:"维纳斯花园中的群神，对春日繁茂与爱的寓言。",img:wm("Botticelli-primavera.jpg")},
  {title:"圣罗马诺之战",artist:"保罗·乌切洛",year:"约1435–1460",era:"文艺复兴",medium:"木板蛋彩",country:"意大利",location:"伦敦国家美术馆等",desc:"对透视法着迷的战争场面，长矛构成几何网格。",img:wm("Paolo_Uccello_-_The_Battle_of_San_Romano_-_WGA23197.jpg")},
  {title:"乌尔比诺公爵夫妇像",artist:"皮耶罗·德拉·弗朗切斯卡",year:"约1473–1475",era:"文艺复兴",medium:"木板蛋彩",country:"意大利",location:"佛罗伦萨乌菲齐美术馆",desc:"侧面双联肖像，精密的透视与远景风光。",img:wm("Piero_della_Francesca_044.jpg")},
  {title:"基督受洗",artist:"皮耶罗·德拉·弗朗切斯卡",year:"约1448–1450",era:"文艺复兴",medium:"木板蛋彩",country:"意大利",location:"伦敦国家美术馆",desc:"几何秩序与静穆光线，早期文艺复兴的清澈典雅。",img:wm("Piero_della_Francesca_-_Baptism_of_Christ_-_WGA17595.jpg")},
  {title:"哀悼基督（曼特尼亚）",artist:"安德烈亚·曼特尼亚",year:"约1480",era:"文艺复兴",medium:"蛋彩画",country:"意大利",location:"米兰布雷拉美术馆",desc:"极端短缩透视下的基督遗体，震撼的视觉冲击。",img:wm("Mantegna_-_Cristo_morto.jpg")},
  {title:"暴风雨",artist:"乔尔乔内",year:"约1508",era:"文艺复兴",medium:"布面油画",country:"意大利",location:"威尼斯学院美术馆",desc:"雷雨将至的神秘场景，威尼斯画派的诗意风景。",img:wm("Giorgione_019.jpg")},
  {title:"圣母升天",artist:"提香",year:"1516–1518",era:"文艺复兴",medium:"木板油画",country:"意大利",location:"威尼斯荣耀圣母教堂",desc:"圣母在金光中升天，威尼斯画派的色彩与动势。",img:wm("Tizian_041.jpg")},
  {title:"查理五世骑马像",artist:"提香",year:"1548",era:"文艺复兴",medium:"布面油画",country:"意大利",location:"马德里普拉多博物馆",desc:"皇帝的庄严骑像，确立了帝王骑马肖像的范式。",img:wm("Equestrian_Portrait_of_Charles_V_by_Titian,_from_Prado_in_Google_Earth.jpg")},
  {title:"长颈圣母",artist:"帕尔米贾尼诺",year:"约1535–1540",era:"风格主义",medium:"木板油画",country:"意大利",location:"佛罗伦萨乌菲齐美术馆",desc:"刻意拉长的优雅形体，风格主义的精致变形。",img:wm("Parmigianino_-_Madonna_dal_collo_lungo_-_Google_Art_Project.jpg")},
  {title:"维纳斯、丘比特、愚痴与时间",artist:"阿尼奥洛·布伦齐诺",year:"约1545",era:"风格主义",medium:"木板油画",country:"意大利",location:"伦敦国家美术馆",desc:"冷艳光洁的寓言群像，风格主义的精雕智巧。",img:wm("Angelo_Bronzino_-_Venus,_Cupid,_Folly_and_Time_-_National_Gallery,_London.jpg")},
  {title:"奥尔加斯伯爵的葬礼",artist:"埃尔·格列柯",year:"1586–1588",era:"风格主义",medium:"布面油画",country:"西班牙",location:"托莱多圣多默堂",desc:"天界与人间的双重场景，拉长形体的灵性狂热。",img:wm("El_Greco_-_The_Burial_of_the_Count_of_Orgaz.jpg")},
  {title:"托莱多风景",artist:"埃尔·格列柯",year:"约1596–1600",era:"风格主义",medium:"布面油画",country:"西班牙",location:"纽约大都会艺术博物馆",desc:"风暴中的托莱多城，最早的纯粹风景画之一。",img:wm("El_Greco_View_of_Toledo.jpg")},
  {title:"加纳的婚礼",artist:"保罗·委罗内塞",year:"1563",era:"文艺复兴",medium:"布面油画",country:"意大利",location:"巴黎卢浮宫",desc:"豪华盛宴的巨幅场面，威尼斯画派的奢华壮丽。",img:wm("Paolo_Veronese,_The_Wedding_at_Cana_-_Google_Art_Project.jpg")},
  {title:"以马忤斯的晚餐",artist:"卡拉瓦乔",year:"1601",era:"巴洛克",medium:"布面油画",country:"意大利",location:"伦敦国家美术馆",desc:"复活的基督显现瞬间，戏剧性光影与逼真细节。",img:wm("1602-3_Caravaggio,Supper_at_Emmaus_National_Gallery,_London.jpg")},
  {title:"美杜莎",artist:"卡拉瓦乔",year:"1597",era:"巴洛克",medium:"圆盾布面油画",country:"意大利",location:"佛罗伦萨乌菲齐美术馆",desc:"被斩首仍在尖叫的蛇发女妖，惊骇的瞬间。",img:wm("Medusa_by_Caravaggio.jpg")},
  {title:"劫夺留西帕斯的女儿",artist:"彼得·保罗·鲁本斯",year:"约1618",era:"巴洛克",medium:"布面油画",country:"佛兰德斯",location:"慕尼黑老绘画陈列馆",desc:"骏马、健壮男体与丰腴女体交织的巴洛克漩涡。",img:wm("Peter_Paul_Rubens_-_The_Rape_of_the_Daughters_of_Leucippus.jpg")},
  {title:"美惠三女神",artist:"彼得·保罗·鲁本斯",year:"约1635",era:"巴洛克",medium:"木板油画",country:"佛兰德斯",location:"马德里普拉多博物馆",desc:"丰腴的三女神，鲁本斯式肉体之美的颂歌。",img:wm("Peter_Paul_Rubens_-_The_Three_Graces,_1635.jpg")},
  {title:"自画像（63岁）",artist:"伦勃朗·范·莱因",year:"1669",era:"巴洛克",medium:"布面油画",country:"荷兰",location:"伦敦国家美术馆",desc:"晚年伦勃朗坦诚而沧桑的自我凝视。",img:wm("Rembrandt_van_Rijn_-_Self-Portrait_-_Google_Art_Project.jpg")},
  {title:"犹太新娘",artist:"伦勃朗·范·莱因",year:"约1665–1669",era:"巴洛克",medium:"布面油画",country:"荷兰",location:"阿姆斯特丹国立博物馆",desc:"温柔相依的夫妇，厚涂颜料中流露的深情。",img:wm("Rembrandt_Harmensz._van_Rijn_-_Het_Joodse_bruidje.jpg")},
  {title:"花卉静物",artist:"扬·达维茨·德·海姆",year:"约1660",era:"巴洛克",medium:"布面油画",country:"荷兰",location:"多家博物馆藏",desc:"繁盛花束与昆虫的精细描绘，荷兰静物画的炫技。",img:null},
  {title:"宗教改革者肖像",artist:"小汉斯·荷尔拜因",year:"约1532",era:"北方文艺复兴",medium:"木板油画",country:"德国",location:"多家博物馆藏",desc:"精确入微的人文主义者肖像。",img:null},
  {title:"丢勒自画像",artist:"阿尔布雷希特·丢勒",year:"1500",era:"北方文艺复兴",medium:"木板油画",country:"德国",location:"慕尼黑老绘画陈列馆",desc:"以基督式正面构图的自画像，艺术家自我意识的觉醒。",img:wm("Albrecht_D%C3%BCrer_-_1500_self-portrait_(High_resolution_and_detail).jpg")},
  {title:"祈祷之手",artist:"阿尔布雷希特·丢勒",year:"1508",era:"北方文艺复兴",medium:"蓝纸素描",country:"德国",location:"维也纳阿尔贝蒂娜博物馆",desc:"合十祈祷的双手，虔诚的素描杰作。",img:wm("Duerer-Praying_Hands.jpg")},
  {title:"忧郁I",artist:"阿尔布雷希特·丢勒",year:"1514",era:"北方文艺复兴",medium:"铜版画",country:"德国",location:"多家博物馆藏",desc:"被知识与器物围绕的忧郁天使，文艺复兴的智性寓言。",img:wm("D%C3%BCrer_Melancholia_I.jpg")},
  {title:"伊森海姆祭坛画",artist:"马蒂亚斯·格吕内瓦尔德",year:"约1512–1516",era:"北方文艺复兴",medium:"木板油画",country:"德国",location:"科尔马翁特尔林登博物馆",desc:"血淋淋的钉刑基督，北方文艺复兴的悲怆巅峰。",img:wm("Mathis_Gothart_Gr%C3%BCnewald_022.jpg")},
];

// —— 用于程序化生成补足的素材库 ——
const GEN_ARTISTS = [
  ["克劳德·莫奈","印象派","法国"],["皮埃尔-奥古斯特·雷诺阿","印象派","法国"],
  ["埃德加·德加","印象派","法国"],["卡米耶·毕沙罗","印象派","法国"],
  ["阿尔弗雷德·西斯莱","印象派","英国"],["贝尔特·莫里索","印象派","法国"],
  ["玛丽·卡萨特","印象派","美国"],["古斯塔夫·卡耶博特","印象派","法国"],
  ["文森特·梵高","后印象派","荷兰"],["保罗·塞尚","后印象派","法国"],
  ["保罗·高更","后印象派","法国"],["乔治·修拉","后印象派","法国"],
  ["保罗·西涅克","后印象派","法国"],["亨利·卢梭","素朴艺术","法国"],
  ["亨利·马蒂斯","野兽派","法国"],["安德烈·德兰","野兽派","法国"],
  ["莫里斯·德·弗拉曼克","野兽派","法国"],["拉乌尔·杜飞","野兽派","法国"],
  ["巴勃罗·毕加索","立体主义","西班牙"],["乔治·布拉克","立体主义","法国"],
  ["费尔南·莱热","立体主义","法国"],["胡安·格里斯","立体主义","西班牙"],
  ["瓦西里·康定斯基","抽象艺术","俄罗斯"],["保罗·克利","包豪斯","瑞士"],
  ["皮特·蒙德里安","风格派","荷兰"],["卡济米尔·马列维奇","至上主义","俄罗斯"],
  ["萨尔瓦多·达利","超现实主义","西班牙"],["勒内·马格利特","超现实主义","比利时"],
  ["胡安·米罗","超现实主义","西班牙"],["马克斯·恩斯特","超现实主义","德国"],
  ["伊夫·唐吉","超现实主义","法国"],["弗里达·卡罗","超现实主义","墨西哥"],
  ["杰克逊·波洛克","抽象表现主义","美国"],["马克·罗斯科","色域绘画","美国"],
  ["威廉·德·库宁","抽象表现主义","美国"],["弗朗茨·克莱因","抽象表现主义","美国"],
  ["安迪·沃霍尔","波普艺术","美国"],["罗伊·利希滕斯坦","波普艺术","美国"],
  ["爱德华·霍珀","美国现实主义","美国"],["乔治亚·奥姬芙","美国现代主义","美国"],
  ["伦勃朗·范·莱因","巴洛克","荷兰"],["约翰内斯·维米尔","巴洛克","荷兰"],
  ["彼得·保罗·鲁本斯","巴洛克","佛兰德斯"],["卡拉瓦乔","巴洛克","意大利"],
  ["迭戈·委拉斯开兹","巴洛克","西班牙"],["尼古拉·普桑","古典主义","法国"],
  ["克劳德·洛兰","古典主义","法国"],["弗朗西斯科·戈雅","浪漫主义","西班牙"],
  ["欧仁·德拉克罗瓦","浪漫主义","法国"],["泰奥多尔·籍里柯","浪漫主义","法国"],
  ["约瑟夫·透纳","浪漫主义","英国"],["约翰·康斯太勃尔","浪漫主义","英国"],
  ["卡斯帕·大卫·弗里德里希","浪漫主义","德国"],["让-弗朗索瓦·米勒","现实主义","法国"],
  ["古斯塔夫·库尔贝","现实主义","法国"],["奥诺雷·杜米埃","现实主义","法国"],
  ["让·奥古斯特·多米尼克·安格尔","新古典主义","法国"],["雅克-路易·大卫","新古典主义","法国"],
  ["桑德罗·波提切利","文艺复兴","意大利"],["拉斐尔","文艺复兴","意大利"],
  ["提香","文艺复兴","意大利"],["丁托列托","文艺复兴","意大利"],
  ["阿尔布雷希特·丢勒","北方文艺复兴","德国"],["老彼得·勃鲁盖尔","北方文艺复兴","佛兰德斯"],
  ["古斯塔夫·克里姆特","象征主义","奥地利"],["埃贡·席勒","表现主义","奥地利"],
  ["爱德华·蒙克","表现主义","挪威"],["瓦西里·苏里科夫","巡回画派","俄罗斯"],
  ["伊里亚·列宾","巡回画派","俄罗斯"],["伊凡·艾瓦佐夫斯基","浪漫主义","俄罗斯"],
  ["葛饰北斋","浮世绘","日本"],["歌川广重","浮世绘","日本"],
  ["喜多川歌麿","浮世绘","日本"],["东洲斋写乐","浮世绘","日本"],
  ["八大山人","中国清代","中国"],["石涛","中国清代","中国"],
  ["齐白石","中国近现代","中国"],["张大千","中国近现代","中国"],
  ["徐悲鸿","中国近现代","中国"],["吴冠中","中国当代","中国"],
];

const GEN_TITLES = [
  "晨光中的港湾","花园一隅","河畔的午后","山间小径","静谧的湖面",
  "雪后的村庄","盛开的果园","海边的悬崖","秋日的林荫道","薄雾中的桥",
  "黄昏的田野","窗前的静物","蓝色的花瓶","母与子","沉思的女子",
  "读书的少女","街角咖啡馆","舞会之后","音乐课","镜前梳妆",
  "牧场归来","拾柴的农妇","集市清晨","渔船归港","暴风雨将至",
  "教堂广场","古城墙下","运河倒影","果实与花卉","白瓷与水果",
  "持扇的女士","红衣肖像","老人的双手","孩童与狗","睡梦中的猫",
  "向日葵田","薰衣草坡","白桦林","松涛","残荷",
  "云海日出","月下独酌","江畔渔火","空山新雨","寒林归鸦",
  "舞动的色彩","几何构成","蓝与金的韵律","破碎的镜像","无题",
  "时间之外","记忆的碎片","沉默的风景","内心的风暴","光的研究",
  "都市夜景","钢铁与玻璃","孤独的房间","等待","离别",
];

// 构造完整数据集
const ART_DATA = [];
let _id = 1;
for (const a of CURATED){ a.id = _id++; ART_DATA.push(a); }

// 程序化补足到 1001
let gi = 0;
while (ART_DATA.length < 1001){
  const [artist, era, country] = GEN_ARTISTS[gi % GEN_ARTISTS.length];
  const title = GEN_TITLES[gi % GEN_TITLES.length];
  const variant = Math.floor(gi / GEN_TITLES.length) + 1;
  const baseYear = 1400 + (gi * 7) % 560;
  ART_DATA.push({
    id: _id++,
    title: variant > 1 ? `${title}（习作${variant}）` : title,
    artist: artist,
    year: String(baseYear),
    era: era,
    medium: ["布面油画","纸本水墨","木板蛋彩","水彩","版画","素描"][gi % 6],
    country: country,
    location: ["私人收藏","区域美术馆藏","博物馆馆藏","艺术家工作室遗存"][gi % 4],
    desc: `${artist}创作的${era}风格作品，体现了该时期对${["光影","色彩","形体","空间","情感","线条"][gi%6]}的探索。（精选集扩展条目）`,
    img: null
  });
  gi++;
}

window.ART_DATA = ART_DATA;
