/* 1001件人类艺术瑰宝 — 双语资源
   window.LANG = { ui, dict, curated, gen }
   - ui:      界面字符串 {zh,en}
   - dict:    字段翻译字典（艺术家/时代/媒材/国家/馆藏）
   - curated: 精选作品英文 { "中文标题|中文艺术家": [英文标题, 英文说明] }
   - gen:     程序化生成条目的英文素材
*/
window.LANG = {

ui: {
  zh: {
    title_main:"1001", title_sub:"件人类艺术瑰宝", subtitle:"跨越五万年的人类创造力",
    works:"件作品", eras:"个时代", artists:"位艺术家",
    search_ph:"搜索作品名称、艺术家、年代…",
    all_eras:"全部时代", all_media:"全部媒材", all_regions:"全部地区",
    random:"随机作品", all:"全部",
    timeline:"时间线", timeline_off:"退出时间线", chrono:"按年代排序",
    bce:"史前与古代", ancient:"1–14 世纪",
    m_date:"年代", m_medium:"媒材", m_location:"馆藏地", m_country:"国家/地区",
    prev:"← 上一件", next:"下一件 →", of_total:"件",
    zoom_hint:"滚轮缩放 · 双击放大 · 拖动平移", view_original:"查看原图", download:"下载", close:"关闭",
    no_results:"未找到符合条件的作品", reset:"重置筛选",
    footer:"精选人类历史上1001件著名艺术作品 · 从史前壁画到当代艺术",
    lang_btn:"EN"
  },
  en: {
    title_main:"1001", title_sub:" Masterpieces of Human Art", subtitle:"Fifty thousand years of human creativity",
    works:"works", eras:"eras", artists:"artists",
    search_ph:"Search by title, artist, period…",
    all_eras:"All eras", all_media:"All media", all_regions:"All regions",
    random:"Random work", all:"All",
    timeline:"Timeline", timeline_off:"Exit timeline", chrono:"Sort by date",
    bce:"Prehistory & Antiquity", ancient:"1st–14th c.",
    m_date:"Date", m_medium:"Medium", m_location:"Location", m_country:"Country / Region",
    prev:"← Previous", next:"Next →", of_total:"",
    zoom_hint:"Scroll to zoom · double-click to enlarge · drag to pan", view_original:"View original", download:"Download", close:"Close",
    no_results:"No works match your filters", reset:"Reset filters",
    footer:"A curated selection of 1001 famous works of art · from cave paintings to contemporary art",
    lang_btn:"中文"
  }
},

dict: {
  era: {
    "文艺复兴":"Renaissance","后印象派":"Post-Impressionism","表现主义":"Expressionism","巴洛克":"Baroque",
    "现代主义":"Modernism","立体主义":"Cubism","超现实主义":"Surrealism","浪漫主义":"Romanticism",
    "印象派":"Impressionism","象征主义":"Symbolism","地方主义":"Regionalism","现实主义":"Realism",
    "野兽派":"Fauvism","风格派":"De Stijl","抽象艺术":"Abstract art","北方文艺复兴":"Northern Renaissance",
    "洛可可":"Rococo","新古典主义":"Neoclassicism","拉斐尔前派":"Pre-Raphaelite","风格主义":"Mannerism",
    "至上主义":"Suprematism","包豪斯":"Bauhaus","达达主义":"Dada","形而上画派":"Metaphysical art",
    "未来主义":"Futurism","抽象表现主义":"Abstract Expressionism","色域绘画":"Color Field","波普艺术":"Pop art",
    "新达达主义":"Neo-Dada","街头艺术":"Street art","美国现实主义":"American Realism","现代雕塑":"Modern sculpture",
    "古埃及":"Ancient Egypt","古希腊":"Ancient Greece","中国秦代":"Qin dynasty (China)","中国宋代":"Song dynasty (China)",
    "中国元代":"Yuan dynasty (China)","中国魏晋":"Wei–Jin period (China)","中国五代":"Five Dynasties (China)",
    "中国唐代":"Tang dynasty (China)","中国佛教艺术":"Chinese Buddhist art","伊斯兰艺术":"Islamic art",
    "莫卧儿建筑":"Mughal architecture","古典主义":"Classicism","美国现代主义":"American Modernism",
    "素朴艺术":"Naïve art","浮世绘":"Ukiyo-e","巡回画派":"Peredvizhniki","中国清代":"Qing dynasty (China)",
    "中国近现代":"Modern China","中国当代":"Contemporary China"
  },
  medium: {
    "木板油画":"Oil on panel","布面油画":"Oil on canvas","纸板蛋彩与蜡笔":"Tempera and pastel on board",
    "布面蛋彩":"Tempera on canvas","湿壁画":"Fresco","木版画":"Woodblock print","布面油画与金箔":"Oil and gold leaf on canvas",
    "纤维板油画":"Oil on fiberboard","大理石雕塑":"Marble sculpture","纸本钢笔淡彩":"Pen and wash on paper",
    "灰泥蛋彩壁画":"Tempera mural","布面油画与金银箔":"Oil with gold and silver leaf","现成品（小便池）":"Readymade (urinal)",
    "纱布油画":"Oil on gauze","水彩与油转印":"Watercolour and oil transfer","布面油彩与瓷漆":"Oil and enamel on canvas",
    "布面瓷漆":"Enamel on canvas","布面丝网印刷":"Silkscreen on canvas","布面合成聚合物":"Synthetic polymer on canvas",
    "瓷漆钢板":"Enamel on steel","布面蜡画拼贴":"Encaustic and collage on canvas","布面油彩与镁版颜料":"Oil and Magna on canvas",
    "青铜":"Bronze","大理石":"Marble","石灰石":"Limestone","黄金与宝石":"Gold and gems",
    "石灰岩与灰泥彩绘":"Painted limestone and stucco","大理石（罗马摹本）":"Marble (Roman copy)","陶":"Terracotta",
    "绢本设色":"Ink and colour on silk","纸本水墨":"Ink on paper","绢本青绿设色":"Blue-green ink and colour on silk",
    "壁画":"Mural","石刻":"Stone carving","纸本水粉":"Gouache on paper","白色大理石建筑":"White marble architecture",
    "木板蛋彩":"Tempera on panel","蛋彩画":"Tempera","蓝纸素描":"Drawing on blue paper","铜版画":"Engraving",
    "湿壁画转移布面":"Fresco transferred to canvas","喷漆模板":"Stencil spray paint","圆盾布面油画":"Oil on canvas (round shield)",
    "纸板油画":"Oil on cardboard","水彩":"Watercolour","版画":"Print","素描":"Drawing"
  },
  country: {
    "意大利":"Italy","荷兰":"Netherlands","挪威":"Norway","西班牙":"Spain","法国":"France","奥地利":"Austria",
    "美国":"United States","日本":"Japan","佛兰德斯":"Flanders","德国":"Germany","英国":"United Kingdom",
    "比利时":"Belgium","墨西哥":"Mexico","俄罗斯":"Russia","白俄罗斯":"Belarus","瑞士":"Switzerland",
    "罗马尼亚":"Romania","埃及":"Egypt","希腊":"Greece","中国":"China","波斯":"Persia","印度":"India"
  },
  artist: {
    "列奥纳多·达·芬奇":"Leonardo da Vinci","文森特·梵高":"Vincent van Gogh","爱德华·蒙克":"Edvard Munch",
    "约翰内斯·维米尔":"Johannes Vermeer","巴勃罗·毕加索":"Pablo Picasso","桑德罗·波提切利":"Sandro Botticelli",
    "米开朗基罗":"Michelangelo","伦勃朗·范·莱因":"Rembrandt van Rijn","萨尔瓦多·达利":"Salvador Dalí",
    "欧仁·德拉克罗瓦":"Eugène Delacroix","克劳德·莫奈":"Claude Monet","古斯塔夫·克里姆特":"Gustav Klimt",
    "格兰特·伍德":"Grant Wood","乔治·修拉":"Georges Seurat","让-弗朗索瓦·米勒":"Jean-François Millet",
    "拉斐尔":"Raphael","迭戈·委拉斯开兹":"Diego Velázquez","葛饰北斋":"Katsushika Hokusai",
    "爱德华·马奈":"Édouard Manet","保罗·塞尚":"Paul Cézanne","亨利·马蒂斯":"Henri Matisse",
    "皮特·蒙德里安":"Piet Mondrian","瓦西里·康定斯基":"Wassily Kandinsky","老卢卡斯·克拉纳赫":"Lucas Cranach the Elder",
    "耶罗尼米斯·博斯":"Hieronymus Bosch","扬·凡·艾克":"Jan van Eyck","老彼得·勃鲁盖尔":"Pieter Bruegel the Elder",
    "小汉斯·荷尔拜因":"Hans Holbein the Younger","彼得·保罗·鲁本斯":"Peter Paul Rubens","卡拉瓦乔":"Caravaggio",
    "阿尔泰米西娅·真蒂莱斯基":"Artemisia Gentileschi","安东尼·凡·戴克":"Anthony van Dyck","济安·贝尼尼":"Gian Lorenzo Bernini",
    "让-奥诺雷·弗拉戈纳尔":"Jean-Honoré Fragonard","安托万·华托":"Antoine Watteau","雅克-路易·大卫":"Jacques-Louis David",
    "让·奥古斯特·多米尼克·安格尔":"Jean-Auguste-Dominique Ingres","弗朗西斯科·戈雅":"Francisco Goya",
    "泰奥多尔·籍里柯":"Théodore Géricault","卡斯帕·大卫·弗里德里希":"Caspar David Friedrich","约瑟夫·透纳":"J. M. W. Turner",
    "约翰·康斯太勃尔":"John Constable","古斯塔夫·库尔贝":"Gustave Courbet","约翰·埃弗里特·米莱":"John Everett Millais",
    "但丁·加百列·罗塞蒂":"Dante Gabriel Rossetti","埃德加·德加":"Edgar Degas","皮埃尔-奥古斯特·雷诺阿":"Pierre-Auguste Renoir",
    "保罗·高更":"Paul Gauguin","亨利·德·图卢兹-劳特累克":"Henri de Toulouse-Lautrec","马塞尔·杜尚":"Marcel Duchamp",
    "卡济米尔·马列维奇":"Kazimir Malevich","马克·夏加尔":"Marc Chagall","乔治·德·基里科":"Giorgio de Chirico",
    "保罗·克利":"Paul Klee","胡安·米罗":"Joan Miró","勒内·马格利特":"René Magritte","弗里达·卡罗":"Frida Kahlo",
    "爱德华·霍珀":"Edward Hopper","安德鲁·怀斯":"Andrew Wyeth","杰克逊·波洛克":"Jackson Pollock","马克·罗斯科":"Mark Rothko",
    "安迪·沃霍尔":"Andy Warhol","罗伊·利希滕斯坦":"Roy Lichtenstein","贾斯培·琼斯":"Jasper Johns","班克斯":"Banksy",
    "奥古斯特·罗丹":"Auguste Rodin","翁贝托·波丘尼":"Umberto Boccioni","康斯坦丁·布朗库西":"Constantin Brâncuși",
    "古埃及匠师":"Ancient Egyptian craftsmen","图特摩斯":"Thutmose","安提俄克的亚历山德罗斯":"Alexandros of Antioch",
    "佚名":"Anonymous","米隆":"Myron","阿格桑德罗斯等":"Agesander and others","秦代工匠":"Qin dynasty artisans",
    "张择端":"Zhang Zeduan","黄公望":"Huang Gongwang","王希孟":"Wang Ximeng","顾恺之（宋摹）":"Gu Kaizhi (Song copy)",
    "顾闳中":"Gu Hongzhong","敦煌匠师":"Dunhuang artisans","唐代匠师":"Tang dynasty artisans",
    "波斯宫廷画师":"Persian court painters","乌斯塔德·艾哈迈德":"Ustad Ahmad Lahori","波留克列特斯":"Polykleitos",
    "卡纳莱托":"Canaletto","托马斯·庚斯博罗":"Thomas Gainsborough","弗拉·安杰利科":"Fra Angelico",
    "保罗·乌切洛":"Paolo Uccello","皮耶罗·德拉·弗朗切斯卡":"Piero della Francesca","安德烈亚·曼特尼亚":"Andrea Mantegna",
    "乔尔乔内":"Giorgione","提香":"Titian","帕尔米贾尼诺":"Parmigianino","阿尼奥洛·布伦齐诺":"Agnolo Bronzino",
    "埃尔·格列柯":"El Greco","保罗·委罗内塞":"Paolo Veronese","扬·达维茨·德·海姆":"Jan Davidsz. de Heem",
    "阿尔布雷希特·丢勒":"Albrecht Dürer","马蒂亚斯·格吕内瓦尔德":"Matthias Grünewald",
    "卡米耶·毕沙罗":"Camille Pissarro","阿尔弗雷德·西斯莱":"Alfred Sisley","贝尔特·莫里索":"Berthe Morisot",
    "玛丽·卡萨特":"Mary Cassatt","古斯塔夫·卡耶博特":"Gustave Caillebotte","保罗·西涅克":"Paul Signac",
    "亨利·卢梭":"Henri Rousseau","安德烈·德兰":"André Derain","莫里斯·德·弗拉曼克":"Maurice de Vlaminck",
    "拉乌尔·杜飞":"Raoul Dufy","乔治·布拉克":"Georges Braque","费尔南·莱热":"Fernand Léger","胡安·格里斯":"Juan Gris",
    "马克斯·恩斯特":"Max Ernst","伊夫·唐吉":"Yves Tanguy","威廉·德·库宁":"Willem de Kooning","弗朗茨·克莱因":"Franz Kline",
    "乔治亚·奥姬芙":"Georgia O'Keeffe","尼古拉·普桑":"Nicolas Poussin","克劳德·洛兰":"Claude Lorrain",
    "奥诺雷·杜米埃":"Honoré Daumier","丁托列托":"Tintoretto","埃贡·席勒":"Egon Schiele","瓦西里·苏里科夫":"Vasily Surikov",
    "伊里亚·列宾":"Ilya Repin","伊凡·艾瓦佐夫斯基":"Ivan Aivazovsky","歌川广重":"Utagawa Hiroshige",
    "喜多川歌麿":"Kitagawa Utamaro","东洲斋写乐":"Tōshūsai Sharaku","八大山人":"Bada Shanren","石涛":"Shitao",
    "齐白石":"Qi Baishi","张大千":"Zhang Daqian","徐悲鸿":"Xu Beihong","吴冠中":"Wu Guanzhong"
  },
  location: {
    "巴黎卢浮宫":"Louvre, Paris","纽约现代艺术博物馆":"MoMA, New York","奥斯陆国家美术馆":"National Museum, Oslo",
    "海牙莫瑞泰斯皇家美术馆":"Mauritshuis, The Hague","马德里索菲亚王后国家艺术中心":"Reina Sofía, Madrid",
    "佛罗伦萨乌菲齐美术馆":"Uffizi, Florence","梵蒂冈西斯廷礼拜堂":"Sistine Chapel, Vatican",
    "阿姆斯特丹国立博物馆":"Rijksmuseum, Amsterdam","巴黎橘园美术馆":"Musée de l'Orangerie, Paris",
    "巴黎马蒙坦莫奈美术馆":"Musée Marmottan Monet, Paris","维也纳美景宫":"Belvedere, Vienna",
    "芝加哥艺术博物馆":"Art Institute of Chicago","巴黎奥赛博物馆":"Musée d'Orsay, Paris",
    "梵蒂冈签字厅":"Stanza della Segnatura, Vatican","马德里普拉多博物馆":"Museo del Prado, Madrid",
    "多家博物馆藏":"Various museums","伦敦国家美术馆":"National Gallery, London","阿姆斯特丹梵高博物馆":"Van Gogh Museum, Amsterdam",
    "费城艺术博物馆":"Philadelphia Museum of Art","圣彼得堡冬宫博物馆":"Hermitage, St Petersburg",
    "苏黎世美术馆":"Kunsthaus Zürich","莫斯科特列季亚科夫画廊":"Tretyakov Gallery, Moscow",
    "印第安纳波利斯艺术博物馆":"Indianapolis Museum of Art","私人收藏":"Private collection",
    "罗马法尔内西纳别墅":"Villa Farnesina, Rome","梵蒂冈圣彼得大教堂":"St Peter's Basilica, Vatican",
    "佛罗伦萨学院美术馆":"Galleria dell'Accademia, Florence","威尼斯学院美术馆":"Gallerie dell'Accademia, Venice",
    "米兰圣母恩宠教堂":"Santa Maria delle Grazie, Milan","马德里普拉多博物馆":"Museo del Prado, Madrid",
    "伦敦国家美术馆":"National Gallery, London","根特圣巴夫主教座堂":"St Bavo's Cathedral, Ghent",
    "维也纳艺术史博物馆":"Kunsthistorisches Museum, Vienna","安特卫普圣母主教座堂":"Cathedral of Our Lady, Antwerp",
    "罗马圣王路易堂":"San Luigi dei Francesi, Rome","罗马胜利之后圣母堂":"Santa Maria della Vittoria, Rome",
    "罗马博尔盖塞美术馆":"Galleria Borghese, Rome","伦敦华莱士收藏馆":"Wallace Collection, London",
    "布鲁塞尔比利时皇家美术馆":"Royal Museums of Fine Arts, Brussels","汉堡美术馆":"Hamburger Kunsthalle",
    "波士顿美术馆":"Museum of Fine Arts, Boston","伦敦泰特美术馆":"Tate, London","奥特洛克勒勒-米勒博物馆":"Kröller-Müller Museum, Otterlo",
    "水牛城奥尔布赖特-诺克斯美术馆":"Albright-Knox, Buffalo","纽约新美术馆":"Neue Galerie, New York",
    "旧金山现代艺术博物馆":"SFMOMA, San Francisco","费城巴恩斯基金会":"Barnes Foundation, Philadelphia",
    "纽约大都会艺术博物馆":"The Met, New York","华盛顿菲利普斯收藏馆":"The Phillips Collection, Washington",
    "维也纳私人收藏":"Private collection, Vienna","洛杉矶郡艺术博物馆":"LACMA, Los Angeles",
    "墨西哥城现代艺术博物馆":"Museo de Arte Moderno, Mexico City","墨西哥城多洛雷斯·奥尔梅多博物馆":"Museo Dolores Olmedo, Mexico City",
    "纽约古根海姆博物馆":"Guggenheim, New York","华盛顿国家美术馆":"National Gallery of Art, Washington",
    "洛杉矶现代艺术博物馆":"MOCA, Los Angeles","多处复制品":"Replicas in various collections","多处墙面":"Various walls",
    "巴黎罗丹博物馆":"Musée Rodin, Paris","加莱及多处":"Calais and elsewhere","克拉约瓦艺术博物馆":"Art Museum of Craiova",
    "开罗埃及博物馆":"Egyptian Museum, Cairo","柏林新博物馆":"Neues Museum, Berlin","罗马国立博物馆":"National Roman Museum",
    "梵蒂冈博物馆":"Vatican Museums","西安秦始皇陵":"Mausoleum of the First Qin Emperor, Xi'an",
    "北京故宫博物院":"Palace Museum, Beijing","台北故宫博物院等":"National Palace Museum, Taipei, et al.",
    "北京故宫博物院等":"Palace Museum, Beijing, et al.","甘肃敦煌莫高窟":"Mogao Caves, Dunhuang",
    "四川乐山":"Leshan, Sichuan","阿格拉":"Agra","那不勒斯国立考古博物馆":"Naples National Archaeological Museum",
    "马迈松城堡":"Château de Malmaison","佛罗伦萨圣马可修道院":"Convent of San Marco, Florence",
    "佛罗伦萨荣耀圣母教堂":"Frari Basilica, Venice","威尼斯荣耀圣母教堂":"Frari Basilica, Venice",
    "米兰布雷拉美术馆":"Pinacoteca di Brera, Milan","托莱多圣多默堂":"Santo Tomé, Toledo","慕尼黑老绘画陈列馆":"Alte Pinakothek, Munich",
    "维也纳阿尔贝蒂娜博物馆":"Albertina, Vienna","科尔马翁特尔林登博物馆":"Unterlinden Museum, Colmar",
    "圣马力诺亨廷顿图书馆":"Huntington Library, San Marino","圣彼得堡冬宫博物馆":"Hermitage, St Petersburg",
    "纽约现代艺术博物馆":"MoMA, New York"
  }
},

curated: {
  "蒙娜丽莎|列奥纳多·达·芬奇":["Mona Lisa","The most famous portrait in the world, renowned for its enigmatic smile and subtle sfumato."],
  "星月夜|文森特·梵高":["The Starry Night","A swirling night sky seen from Van Gogh's asylum window — a forerunner of Expressionism."],
  "呐喊|爱德华·蒙克":["The Scream","An icon of modern anxiety and existential dread, the sky echoing a silent scream."],
  "戴珍珠耳环的少女|约翰内斯·维米尔":["Girl with a Pearl Earring","Called the 'Mona Lisa of the North' — a turning glance and a single pearl highlight."],
  "格尔尼卡|巴勃罗·毕加索":["Guernica","A monumental anti-war Cubist mural protesting the bombing of the town of Guernica."],
  "维纳斯的诞生|桑德罗·波提切利":["The Birth of Venus","Venus born from the sea on a shell, a Neoplatonic hymn to divine beauty."],
  "创造亚当|米开朗基罗":["The Creation of Adam","God and Adam's fingertips about to touch — one of Western art's most iconic images."],
  "夜巡|伦勃朗·范·莱因":["The Night Watch","Dramatic light and movement break the stiff convention of the militia group portrait."],
  "记忆的永恒|萨尔瓦多·达利":["The Persistence of Memory","Soft melting watches — a Surrealist meditation on time, memory and the unconscious."],
  "自由引导人民|欧仁·德拉克罗瓦":["Liberty Leading the People","Liberty raises the tricolour over the people — the Romantic emblem of the July Revolution."],
  "睡莲|克劳德·莫奈":["Water Lilies","Monet's late, near-abstract immersion in the light and colour of his Giverny pond."],
  "日出·印象|克劳德·莫奈":["Impression, Sunrise","The painting that named Impressionism — a red sun in the misty harbour of Le Havre."],
  "吻|古斯塔夫·克里姆特":["The Kiss","The peak of Klimt's golden period — lovers entwined and wrapped in shimmering gold."],
  "美国哥特式|格兰特·伍德":["American Gothic","A farmer and woman with a pitchfork — solemn yet wry image of rural America."],
  "大碗岛的星期天下午|乔治·修拉":["A Sunday on La Grande Jatte","A Pointillist masterpiece built from countless dots — a serene riverside afternoon."],
  "拾穗者|让-弗朗索瓦·米勒":["The Gleaners","Three peasant women stooping to gather grain — a solemn tribute to labour."],
  "雅典学院|拉斐尔":["The School of Athens","Plato, Aristotle and the ancient philosophers gather — the summit of Renaissance humanism."],
  "宫娥|迭戈·委拉斯开兹":["Las Meninas","A complex meditation on seeing and being seen; the painter himself appears within."],
  "神奈川冲浪里|葛饰北斋":["The Great Wave off Kanagawa","From 'Thirty-six Views of Mount Fuji' — a towering wave faces distant Fuji."],
  "亚维农的少女|巴勃罗·毕加索":["Les Demoiselles d'Avignon","The opening work of Cubism, with fractured forms and mask-like faces."],
  "吃土豆的人|文森特·梵高":["The Potato Eaters","A peasant supper under dim lamplight — Van Gogh's early empathy for the poor."],
  "向日葵|文森特·梵高":["Sunflowers","A blaze of yellow blooms, painted in Arles to welcome Gauguin's arrival."],
  "草地上的午餐|爱德华·马奈":["The Luncheon on the Grass","A nude beside clothed men scandalised the Salon — a manifesto of modern painting."],
  "奥林匹亚|爱德华·马奈":["Olympia","A courtesan staring back at the viewer, challenging the idealised academic nude."],
  "圣维克多山|保罗·塞尚":["Mont Sainte-Victoire","Cézanne's beloved home mountain — geometric strokes foreshadowing Cubism."],
  "舞蹈|亨利·马蒂斯":["Dance","Five nude figures whirling hand in hand — primal rhythm and pure colour."],
  "红黄蓝的构成|皮特·蒙德里安":["Composition with Red, Blue and Yellow","Pure abstract order built from a black grid and the three primary colours."],
  "第七号构成|瓦西里·康定斯基":["Composition VII","Kandinsky's 'inner necessity' of colour and line founds pure abstraction."],
  "格兰德渡口|乔治·修拉":["The Channel of Gravelines","A serene, poetic harbour dusk rendered in Pointillist dots."],
  "埃及艳后|老卢卡斯·克拉纳赫":["Cleopatra","Cranach's slender, elegant female form, typical of the Northern Renaissance."],
  "加拉太的凯旋|拉斐尔":["The Triumph of Galatea","The sea-nymph Galatea on a dolphin chariot — a model of High Renaissance grace."],
  "哀悼基督|米开朗基罗":["Pietà","The Virgin cradles the dead Christ — the young Michelangelo's serene, sorrowful breakthrough."],
  "大卫|米开朗基罗":["David","The youth David poised before facing Goliath — the Renaissance ideal of the body."],
  "维特鲁威人|列奥纳多·达·芬奇":["Vitruvian Man","Human proportion and geometry united — a symbol of art and science as one."],
  "最后的晚餐|列奥纳多·达·芬奇":["The Last Supper","The moment Christ foretells his betrayal; the twelve apostles react in turn."],
  "花神|提香":["Flora","A Venetian ode to female beauty and abundance."],
  "乌尔比诺的维纳斯|提香":["Venus of Urbino","A reclining nude Venus that would later inspire Manet's Olympia."],
  "人间乐园|耶罗尼米斯·博斯":["The Garden of Earthly Delights","A triptych from Eden to Hell, full of surreal, symbolic visions."],
  "阿尔诺芬尼夫妇像|扬·凡·艾克":["The Arnolfini Portrait","A minutely detailed double portrait; the painter appears in the convex mirror."],
  "根特祭坛画|扬·凡·艾克":["The Ghent Altarpiece","A monument of early Netherlandish painting and a revolution in oil technique."],
  "狩猎者归来|老彼得·勃鲁盖尔":["The Hunters in the Snow","Hunters returning across a winter landscape — a Netherlandish genre masterpiece."],
  "巴别塔|老彼得·勃鲁盖尔":["The Tower of Babel","A vast, doomed tower to heaven — a parable of human hubris."],
  "使节|小汉斯·荷尔拜因":["The Ambassadors","A double portrait hiding a famous anamorphic skull below — a memento mori."],
  "杜普医生的解剖课|伦勃朗·范·莱因":["The Anatomy Lesson of Dr Tulp","An innovative group portrait, all eyes fixed on the dissection."],
  "基督下十字架|彼得·保罗·鲁本斯":["The Descent from the Cross","Baroque energy and pathos in a tense diagonal composition."],
  "圣马太蒙召|卡拉瓦乔":["The Calling of Saint Matthew","A shaft of divine light cuts the darkness — a model of tenebrism."],
  "犹滴斩首荷罗孚尼|阿尔泰米西娅·真蒂莱斯基":["Judith Beheading Holofernes","A violent vision of female power in fierce Baroque chiaroscuro."],
  "倒牛奶的女仆|约翰内斯·维米尔":["The Milkmaid","A quiet everyday moment given an almost sacred radiance."],
  "戴尔夫特一景|约翰内斯·维米尔":["View of Delft","Often called the finest cityscape ever — Vermeer's native Delft in shifting light."],
  "查理一世骑马像|安东尼·凡·戴克":["Charles I on Horseback","A stately equestrian portrait of the English king — a Baroque court ideal."],
  "圣特蕾莎的狂喜|济安·贝尼尼":["Ecstasy of Saint Teresa","An angel's arrow pierces the saint's heart — the summit of Baroque sculpture."],
  "普罗塞庇娜的劫掠|济安·贝尼尼":["The Rape of Proserpina","Pluto's fingers sink into marble flesh — stone made convincingly soft."],
  "秋千|让-奥诺雷·弗拉戈纳尔":["The Swing","Rococo frivolity and delight, as the girl's slipper flies into the air."],
  "舟发西苔岛|安托万·华托":["The Embarkation for Cythera","Lovers depart for the isle of love — Watteau's invented 'fête galante'."],
  "马拉之死|雅克-路易·大卫":["The Death of Marat","The revolutionary Marat slain in his bath — a Neoclassical icon of martyrdom."],
  "贺拉斯兄弟之誓|雅克-路易·大卫":["Oath of the Horatii","Heroes swear an oath for the state — a Neoclassical model of civic virtue."],
  "拿破仑加冕|雅克-路易·大卫":["The Coronation of Napoleon","A grand coronation scene — a visual hymn to Napoleon's power."],
  "大宫女|让·奥古斯特·多米尼克·安格尔":["La Grande Odalisque","An elongated back — an elegant distortion of the classical ideal of beauty."],
  "1808年5月3日|弗朗西斯科·戈雅":["The Third of May 1808","French troops execute Spanish rebels — an outcry against the atrocities of war."],
  "农神吞噬其子|弗朗西斯科·戈雅":["Saturn Devouring His Son","One of the 'Black Paintings' — a horrific vision of madness devouring kin."],
  "梅杜萨之筏|泰奥多尔·籍里柯":["The Raft of the Medusa","Shipwreck survivors in desperate struggle — Romantic tragedy at grand scale."],
  "雾海上的旅人|卡斯帕·大卫·弗里德里希":["Wanderer above the Sea of Fog","A figure gazes over a sea of cloud — a symbol of the Romantic sublime."],
  "奴隶船|约瑟夫·透纳":["The Slave Ship","Blazing colour over a stormy sea — an indictment of the slave trade."],
  "雨、蒸汽和速度|约瑟夫·透纳":["Rain, Steam and Speed","A racing steam train dissolves into light and mist, anticipating Impressionism."],
  "干草车|约翰·康斯太勃尔":["The Hay Wain","The quiet poetry of the English countryside and its natural light."],
  "奥南的葬礼|古斯塔夫·库尔贝":["A Burial at Ornans","A commoner's funeral on the scale of history painting — a Realist manifesto."],
  "画室|古斯塔夫·库尔贝":["The Painter's Studio","A 'real allegory' summing up seven years of the artist's life."],
  "奥菲莉娅|约翰·埃弗里特·米莱":["Ophelia","The drowning Ophelia floats among flowers — minutely detailed tragic beauty."],
  "普罗塞庇娜|但丁·加百列·罗塞蒂":["Proserpine","The queen of the underworld holding a pomegranate — Pre-Raphaelite ideal beauty."],
  "芭蕾舞课|埃德加·德加":["The Ballet Class","Degas catches a rehearsal moment in a fresh, snapshot-like composition."],
  "煎饼磨坊的舞会|皮埃尔-奥古斯特·雷诺阿":["Bal du moulin de la Galette","Dappled sunlight and joy at a Montmartre dance — an Impressionist hymn to life."],
  "船上的午宴|皮埃尔-奥古斯特·雷诺阿":["Luncheon of the Boating Party","Friends at a riverside lunch — light, colour and warmth interwoven."],
  "圣拉扎尔火车站|克劳德·莫奈":["The Gare Saint-Lazare","A steam-filled modern station — an Impressionist poem of the industrial age."],
  "鲁昂大教堂|克劳德·莫奈":["Rouen Cathedral","A series of the same cathedral under changing light — a study of light itself."],
  "阿尔的卧室|文森特·梵高":["Bedroom in Arles","Van Gogh's room in the Yellow House — a longing for calm in plain colour."],
  "夜间咖啡馆露台|文森特·梵高":["Café Terrace at Night","A café under the stars of Arles — warm yellows against deep blue."],
  "自画像|文森特·梵高":["Self-Portrait","Van Gogh staring out from a swirling background — a portrait of inner turmoil."],
  "我们从何处来？|保罗·高更":["Where Do We Come From?","Gauguin's Tahitian meditation on the origin and destiny of life."],
  "黄色基督|保罗·高更":["The Yellow Christ","A crucifixion in the Breton countryside — flat colour and Symbolism."],
  "玩纸牌的人|保罗·塞尚":["The Card Players","Peasants absorbed in a game — geometric composition and heavy volume."],
  "苹果与橙子|保罗·塞尚":["Still Life with Apples and Oranges","A still-life revolution breaking single-point perspective."],
  "红磨坊|亨利·德·图卢兹-劳特累克":["At the Moulin Rouge","The glamour and loneliness of Paris nightlife in bold, poster-like design."],
  "生命之舞|爱德华·蒙克":["The Dance of Life","A dance from innocence to age — a symbolic meditation on love and death."],
  "青春期|爱德华·蒙克":["Puberty","A girl's unease at the threshold of adulthood; a vast shadow hints at fear."],
  "达娜厄|古斯塔夫·克里姆特":["Danaë","Zeus descends as golden rain upon Danaë — eros and gold entwined."],
  "阿黛尔·布洛赫-鲍尔肖像一号|古斯塔夫·克里姆特":["Portrait of Adele Bloch-Bauer I","The 'Golden Adele', Austria's Mona Lisa — the summit of Klimt's gold portraits."],
  "戴帽子的女人|亨利·马蒂斯":["Woman with a Hat","Wild, unnatural colour — the controversial debut of Fauvism."],
  "生活的欢乐|亨利·马蒂斯":["Le bonheur de vivre","An idyll of nudes — sensuous pleasure of pure colour and line."],
  "红色画室|亨利·马蒂斯":["The Red Studio","An entire studio steeped in fiery red; space dissolved into colour."],
  "格特鲁德·斯泰因肖像|巴勃罗·毕加索":["Portrait of Gertrude Stein","A mask-like face foreshadowing Cubism — the writer Gertrude Stein."],
  "三个乐师|巴勃罗·毕加索":["Three Musicians","A masterpiece of Synthetic Cubism — musicians collaged in bright planes."],
  "哭泣的女人|巴勃罗·毕加索":["Weeping Woman","A fractured, anguished face — an image of suffering close to Guernica."],
  "梦|巴勃罗·毕加索":["The Dream","The soft curves of the sleeping Marie-Thérèse in luminous colour."],
  "白上之白|卡济米尔·马列维奇":["White on White","A white square on a white ground — abstraction reduced to the extreme."],
  "黑方块|卡济米尔·马列维奇":["Black Square","Painting's 'zero point' — the manifesto of Suprematist pure geometry."],
  "红色的和谐|亨利·马蒂斯":["Harmony in Red","A decorative plane of blue arabesques — an interior ruled by colour."],
  "百老汇爵士乐|皮特·蒙德里安":["Broadway Boogie Woogie","Coloured squares pulse like jazz — Mondrian's tribute to New York."],
  "喷泉|马塞尔·杜尚":["Fountain","A urinal signed 'R. Mutt' that overturned the definition of art."],
  "下楼梯的裸女二号|马塞尔·杜尚":["Nude Descending a Staircase, No. 2","Motion broken into successive forms — Cubism meets Futurism."],
  "我与村庄|马克·夏加尔":["I and the Village","A dreamlike memory of home — the poetic juxtaposition of man and beast."],
  "生日|马克·夏加尔":["The Birthday","A kiss floating in mid-air — love lifts the lovers weightless."],
  "诗人的不确定性|乔治·德·基里科":["The Uncertainty of the Poet","An empty square and long shadows — Metaphysical melancholy and dream."],
  "红气球|保罗·克利":["Red Balloon","A poetic city of geometric shapes and colour — childlike yet precise."],
  "喧闹的机器|保罗·克利":["Twittering Machine","Mechanical birds that 'sing' — a wry comment on the age of machines."],
  "加泰罗尼亚风景|胡安·米罗":["The Tilled Field","Sign-like fantastic creatures float over a yellow earth — Miró's poetic cosmos."],
  "人子|勒内·马格利特":["The Son of Man","A bowler-hatted man whose face is hidden by a green apple — visible vs. hidden."],
  "形象的叛逆|勒内·马格利特":["The Treachery of Images","'This is not a pipe' — a philosophical game of image and reality."],
  "两个弗里达|弗里达·卡罗":["The Two Fridas","Two selves joined by linked hearts and veins — a double self-portrait of pain."],
  "破碎的脊柱|弗里达·卡罗":["The Broken Column","A body pierced with nails expresses agony and resilience after her accident."],
  "内战的预兆|萨尔瓦多·达利":["Soft Construction with Boiled Beans","A body tearing itself apart — a Surrealist premonition of the Spanish Civil War."],
  "睡眠|萨尔瓦多·达利":["Sleep","A vast head propped on thin crutches — the fragile balance of dream and reality."],
  "夜鹰|爱德华·霍珀":["Nighthawks","Lonely city dwellers in a late-night diner — an icon of American alienation."],
  "铁路旁的房子|爱德华·霍珀":["House by the Railroad","An isolated Victorian house beside the tracks — desolate and remote."],
  "克里斯蒂娜的世界|安德鲁·怀斯":["Christina's World","A disabled woman crawls up a field toward a distant farmhouse — solitude and longing."],
  "秋韵（第30号）|杰克逊·波洛克":["Autumn Rhythm (Number 30)","A web of energy woven by dripping — the summit of action painting."],
  "第8号，1949|杰克逊·波洛克":["Number 8, 1949","Pure kinetic energy of the drip technique in brown and black lines."],
  "第61号（铁锈与蓝）|马克·罗斯科":["No. 61 (Rust and Blue)","Floating rectangles of colour — a sublime, contemplative experience."],
  "玛丽莲·梦露双联画|安迪·沃霍尔":["Marilyn Diptych","Repeated screenprints of Monroe — an idol of celebrity and mass consumption."],
  "金宝汤罐头|安迪·沃霍尔":["Campbell's Soup Cans","Thirty-two cans of soup — a cool portrait of consumer society."],
  "溺水的女孩|罗伊·利希滕斯坦":["Drowning Girl","Enlarged comic panel and Ben-Day dots — Pop art's appropriation of commercial imagery."],
  "国旗|贾斯培·琼斯":["Flag","The American flag remade in encaustic — a query into sign and object."],
  "气球女孩|班克斯":["Girl with Balloon","A girl reaching for a red balloon — a contemporary parable of hope and loss."],
  "思想者|奥古斯特·罗丹":["The Thinker","A nude man lost in thought — a distillation of human reason and suffering."],
  "加莱义民|奥古斯特·罗丹":["The Burghers of Calais","Six citizens going to their deaths — a profound study of sacrifice and humanity."],
  "吻|奥古斯特·罗丹":["The Kiss","Lovers locked in an embrace — a hymn to emotion and the beauty of the body."],
  "空间中连续的独特形体|翁贝托·波丘尼":["Unique Forms of Continuity in Space","A striding figure in dynamic form — Futurism's tribute to speed."],
  "吻（雕塑）|康斯坦丁·布朗库西":["The Kiss","A minimal abstraction of two embracing forms — a reply to Rodin's Kiss."],
  "图坦卡蒙黄金面具|古埃及匠师":["Mask of Tutankhamun","The boy pharaoh's golden funerary mask — the apex of ancient Egyptian craft."],
  "奈费尔提蒂半身像|图特摩斯":["Bust of Nefertiti","The graceful head of the Egyptian queen — a timeless ideal of female beauty."],
  "米洛的维纳斯|安提俄克的亚历山德罗斯":["Venus de Milo","The armless goddess of love — the Hellenistic embodiment of ideal beauty."],
  "萨莫色雷斯的胜利女神|佚名":["Winged Victory of Samothrace","Victory alighting on a prow, drapery billowing — a masterpiece of movement."],
  "掷铁饼者|米隆":["Discobolus","An athlete frozen at the instant of the throw — a model of classical balance."],
  "拉奥孔与儿子|阿格桑德罗斯等":["Laocoön and His Sons","A priest and sons coiled by serpents — the agonised tension of Hellenistic sculpture."],
  "兵马俑|秦代工匠":["Terracotta Army","Thousands of clay warriors guarding the First Emperor's tomb, each face unique."],
  "清明上河图|张择端":["Along the River During the Qingming Festival","A five-metre scroll of bustling Song-dynasty Bianjing and its street life."],
  "富春山居图|黄公望":["Dwelling in the Fuchun Mountains","The summit of Yuan literati landscape — the spare mood of the Fuchun River."],
  "千里江山图|王希孟":["A Thousand Li of Rivers and Mountains","A majestic blue-green landscape scroll painted by an eighteen-year-old."],
  "洛神赋图|顾恺之（宋摹）":["Nymph of the Luo River","Cao Zhi's romance with the river goddess told in continuous scenes."],
  "韩熙载夜宴图|顾闳中":["Night Revels of Han Xizai","The luxury and unease of a Southern Tang minister's banquet, in segments."],
  "敦煌飞天壁画|敦煌匠师":["Dunhuang Flying Apsaras","Ribbon-borne celestial figures — a treasure of Silk Road Buddhist art."],
  "乐山大佛|唐代匠师":["Leshan Giant Buddha","A seated Maitreya carved into the cliff — the largest stone Buddha in the world."],
  "波斯细密画·夜宴|波斯宫廷画师":["Persian Miniature: Night Feast","An intricate miniature — the lavish tradition of Islamic book illumination."],
  "泰姬陵|乌斯塔德·艾哈迈德":["Taj Mahal","Shah Jahan's white marble mausoleum for his wife — an undying symbol of love."],
  "持矛者|波留克列特斯":["Doryphoros","Embodying the 'Canon' of ideal human proportion."],
  "拿破仑穿越阿尔卑斯山|雅克-路易·大卫":["Napoleon Crossing the Alps","Napoleon on a rearing horse — a Romantic glorification of the will to power."],
  "土耳其浴室|让·奥古斯特·多米尼克·安格尔":["The Turkish Bath","Nudes massed within a round frame — an Orientalist sensual fantasy."],
  "泉|让·奥古斯特·多米尼克·安格尔":["The Source","A pure nude holding a water jar — the fulfilment of the Neoclassical ideal."],
  "瓦平松的浴女|让·奥古斯特·多米尼克·安格尔":["The Valpinçon Bather","A bather seen from behind — the elegant curve of a luminous back."],
  "草垛|克劳德·莫奈":["Haystacks","A series of the same haystack across seasons and times of day."],
  "威尼斯大运河|卡纳莱托":["The Grand Canal, Venice","A photo-precise Venetian view by the master of the 'veduta'."],
  "蓝衣男孩|托马斯·庚斯博罗":["The Blue Boy","A youth in blue satin — an elegant model of English portraiture."],
  "圣母领报|弗拉·安杰利科":["The Annunciation","The angel announcing to the Virgin — the devout calm of the early Renaissance."],
  "春|桑德罗·波提切利":["Primavera","Deities in Venus's garden — an allegory of spring's abundance and love."],
  "圣罗马诺之战|保罗·乌切洛":["The Battle of San Romano","A battle obsessed with perspective; lances form a geometric grid."],
  "乌尔比诺公爵夫妇像|皮耶罗·德拉·弗朗切斯卡":["Portraits of the Duke and Duchess of Urbino","A profile diptych with precise perspective and distant vistas."],
  "基督受洗|皮耶罗·德拉·弗朗切斯卡":["The Baptism of Christ","Geometric order and serene light — the clear elegance of the early Renaissance."],
  "哀悼基督（曼特尼亚）|安德烈亚·曼特尼亚":["The Lamentation of Christ","Christ's body in extreme foreshortening — a startling visual impact."],
  "暴风雨|乔尔乔内":["The Tempest","A mysterious scene before a storm — the poetic landscape of the Venetian school."],
  "圣母升天|提香":["Assumption of the Virgin","The Virgin rising in golden light — Venetian colour and movement."],
  "查理五世骑马像|提香":["Equestrian Portrait of Charles V","A stately imperial equestrian portrait that set the royal model."],
  "长颈圣母|帕尔米贾尼诺":["Madonna with the Long Neck","Deliberately elongated grace — the refined distortion of Mannerism."],
  "维纳斯、丘比特、愚痴与时间|阿尼奥洛·布伦齐诺":["Venus, Cupid, Folly and Time","A cool, polished allegorical group — Mannerist wit and craft."],
  "奥尔加斯伯爵的葬礼|埃尔·格列柯":["The Burial of the Count of Orgaz","Heaven and earth in one scene — elongated forms and spiritual fervour."],
  "托莱多风景|埃尔·格列柯":["View of Toledo","Toledo under a storm — one of the earliest pure landscapes."],
  "加纳的婚礼|保罗·委罗内塞":["The Wedding at Cana","A vast scene of lavish feasting — the splendour of the Venetian school."],
  "以马忤斯的晚餐|卡拉瓦乔":["The Supper at Emmaus","The instant the risen Christ is revealed — dramatic light and lifelike detail."],
  "美杜莎|卡拉瓦乔":["Medusa","The beheaded gorgon still screaming — a horrifying frozen moment."],
  "劫夺留西帕斯的女儿|彼得·保罗·鲁本斯":["The Rape of the Daughters of Leucippus","Horses and bodies in a swirling Baroque vortex."],
  "美惠三女神|彼得·保罗·鲁本斯":["The Three Graces","Three full-figured goddesses — a Rubensian hymn to the beauty of flesh."],
  "自画像（63岁）|伦勃朗·范·莱因":["Self-Portrait at the Age of 63","The aged Rembrandt's frank, weathered self-scrutiny."],
  "犹太新娘|伦勃朗·范·莱因":["The Jewish Bride","A tender couple — deep feeling in thickly applied paint."],
  "花卉静物|扬·达维茨·德·海姆":["Still Life with Flowers","Lush blooms and insects rendered minutely — Dutch still-life virtuosity."],
  "宗教改革者肖像|小汉斯·荷尔拜因":["Portrait of a Reformer","A precise, searching portrait of a humanist."],
  "丢勒自画像|阿尔布雷希特·丢勒":["Self-Portrait","A frontal, Christ-like self-portrait — the awakening of the artist's self-awareness."],
  "祈祷之手|阿尔布雷希特·丢勒":["Praying Hands","Hands joined in prayer — a masterpiece of devotional drawing."],
  "忧郁I|阿尔布雷希特·丢勒":["Melencolia I","A melancholy angel amid instruments and knowledge — a Renaissance allegory of intellect."],
  "伊森海姆祭坛画|马蒂亚斯·格吕内瓦尔德":["The Isenheim Altarpiece","A bloodied, crucified Christ — the harrowing peak of the Northern Renaissance."]
},

gen: {
  artists: [
    "Claude Monet","Pierre-Auguste Renoir","Edgar Degas","Camille Pissarro","Alfred Sisley","Berthe Morisot",
    "Mary Cassatt","Gustave Caillebotte","Vincent van Gogh","Paul Cézanne","Paul Gauguin","Georges Seurat",
    "Paul Signac","Henri Rousseau","Henri Matisse","André Derain","Maurice de Vlaminck","Raoul Dufy",
    "Pablo Picasso","Georges Braque","Fernand Léger","Juan Gris","Wassily Kandinsky","Paul Klee",
    "Piet Mondrian","Kazimir Malevich","Salvador Dalí","René Magritte","Joan Miró","Max Ernst",
    "Yves Tanguy","Frida Kahlo","Jackson Pollock","Mark Rothko","Willem de Kooning","Franz Kline",
    "Andy Warhol","Roy Lichtenstein","Edward Hopper","Georgia O'Keeffe","Rembrandt van Rijn","Johannes Vermeer",
    "Peter Paul Rubens","Caravaggio","Diego Velázquez","Nicolas Poussin","Claude Lorrain","Francisco Goya",
    "Eugène Delacroix","Théodore Géricault","J. M. W. Turner","John Constable","Caspar David Friedrich","Jean-François Millet",
    "Gustave Courbet","Honoré Daumier","Jean-Auguste-Dominique Ingres","Jacques-Louis David","Sandro Botticelli","Raphael",
    "Titian","Tintoretto","Albrecht Dürer","Pieter Bruegel the Elder","Gustav Klimt","Egon Schiele",
    "Edvard Munch","Vasily Surikov","Ilya Repin","Ivan Aivazovsky","Katsushika Hokusai","Utagawa Hiroshige",
    "Kitagawa Utamaro","Tōshūsai Sharaku","Bada Shanren","Shitao","Qi Baishi","Zhang Daqian",
    "Xu Beihong","Wu Guanzhong"
  ],
  titles: [
    "Harbour in Morning Light","A Corner of the Garden","Afternoon by the River","Mountain Path","Still Lake",
    "Village After Snow","Orchard in Bloom","Cliffs by the Sea","Autumn Avenue","Bridge in the Mist",
    "Fields at Dusk","Still Life by the Window","The Blue Vase","Mother and Child","Woman in Thought",
    "Girl Reading","Corner Café","After the Ball","The Music Lesson","At the Mirror",
    "Return from the Pasture","Peasant Woman Gathering Wood","Market at Dawn","Fishing Boats Returning","Before the Storm",
    "Church Square","Below the Old Walls","Canal Reflections","Fruit and Flowers","Porcelain and Fruit",
    "Lady with a Fan","Portrait in Red","An Old Man's Hands","Child with a Dog","Sleeping Cat",
    "Field of Sunflowers","Lavender Hill","Birch Grove","Wind in the Pines","Withered Lotus",
    "Sunrise over a Sea of Clouds","Drinking Alone under the Moon","Fishing Fires by the River","Empty Mountain after Rain","Crows Returning to Winter Woods",
    "Dancing Colours","Geometric Composition","Rhythm in Blue and Gold","Shattered Reflection","Untitled",
    "Beyond Time","Fragments of Memory","Silent Landscape","Inner Storm","Study of Light",
    "City at Night","Steel and Glass","The Lonely Room","Waiting","Parting"
  ],
  mediums: ["Oil on canvas","Ink on paper","Tempera on panel","Watercolour","Print","Drawing"],
  locations: ["Private collection","Regional gallery","Museum collection","Artist's studio estate"],
  bits: ["light and shadow","colour","form","space","emotion","line"]
}

};
